### ISSUE TITLE
iOS 6 does not work with gdx-pay 0.9.2 GDX version 1.8.0 RovoVM version 1.12.0 

### ISSUE THREAD

**Issue by coin2** [libgdx/gdx-pay#100]
Tried this today with a non-consumable purchase and it did not work at all. Listeners seem to get either very delayed or not called at all. 

The problem build is: xCode 6.4.2 built on Mars.2
RovoVM version 1.12.0
GDX version 1.8.0
gdx-pay: 0.9..2

Frequent crashing. General mayhem. I've rolled back to 0.8.0 (libgdx version 1.7.0 robovm version 1.8.0) for iOS which appears to work perfectly so far. 

P.S. I'm running an iPod touch with iOS 6. Quite old, I know, but I'm sure some people still have them.

**Comment by keesvandieren** [comment]
Hi,

I have no Apple devices any more with iOS versions older than 8.1, so I cannot test on versions older than that one.

Do you have any error message or stack trace?

22-07-2015 one of Robovm developers wrote:

"Technically we can support iOS 6, but our official support starts with iOS 7."

https://groups.google.com/forum/#!topic/robovm/13C4zRGT3Vg

So I think that anything older than iOS 7 might cause crashes.

**Comment by noblemaster** [comment]
That's a problem of RoboVM that doesn't support anything older than iOS 7. Cannot fix on our end.
