### ISSUE TITLE
Is consuming an consumable Google Play Product supported now?

### ISSUE THREAD

**Issue by mustii82** [libgdx/gdx-pay#101]
I need to do some work and will use this Library but I have to consume the consumable Products. I read at the wiki that consume is not supported. But the wiki looks very outdated so I ask here for help :)

**Comment by junkdog** [comment]
Hmm, it was meant to be cleaned up and pull requested, but it hasn't happened yet  - we've added consumables in our branch: https://github.com/junkdog/gdx-pay/tree/maven

**Comment by noblemaster** [comment]
Looks great! Do you mind sending a pull request to merge it? :)

**Comment by mustii82** [comment]
@junkdog Please do it :+1:

**Comment by TomGrill** [comment]
any updates?

**Comment by deepakraod** [comment]
Any updates on this ? How do we notify consume of Consumables.

**Comment by noblemaster** [comment]
Sorry, still haven't received a pull request from junkdog. Anyone else, please go for it and I'll merge!

**Comment by junkdog** [comment]
Hey, sorry for letting this slip :(

I looked over the code - I don't think it's "production  ready", but I don't have time to clean it up atm.

A couple of caveats:
- we have a partial maven pom (for easier integration with our project)
- unnecessary diffs w.r.t. style, line breaks (we touched a lot of stuff going back and forth)
- a hack to work with fragment applications on android
- no tests of any kind

I'll send the pull request from the top of our branch, but - like I said - probably not merge worthy in its current form, imo.

**Comment by noblemaster** [comment]
Merged - Many thanks :-D

Also, I created a new SNAPSHOT release with the updated GooglePlay project.

**Comment by DavidBVal** [comment]
Any documentation or example shows how to consume the items? First purchase works, then I get handlePurchaseError with the exception: startPurchaseRequest failed at getBuyIntent() for product: xxxxx

**Comment by MrCharli3** [comment]
@DavidBVal Same for me, If I buy my product twice it gives me that error. Any info on this?
