### ISSUE TITLE
After RoboVM -- will there be Multi-OS support?

### ISSUE THREAD

**Issue by rungkutta** [libgdx/gdx-pay#105]
I've used gdx-pay with the RoboVM iOS backend in the past, and it's great. Any advice on what will be required to get this working as libgdx switches to the Multi-OS backend? Is anybody already working on this, or is help needed?

Thanks.

**Comment by noblemaster** [comment]
I haven't looked at Multi-OS yet. If we are lucky, just changing the import declarations should do the trick. I think however some other minor modifications might be needed. I think it should be a fairly easy port.

**Comment by allanstevens** [comment]
Would you know if it works with the new MobiDevelop fork of RoboVM ?  

I'm struggling to get iap working on ios with the standard robovm bindings, so would like to switch to this.

Thanks

**Comment by noblemaster** [comment]
OK, I just switched to the MobiDevelop fork of RoboVM. I tested the sandbox purchases on Apple using gdx-pay and it seems to be working just fine :)

I would say, it's good to go! I'll report & fix errors in case this doesn't work in production.
