### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by infintesoftware** [libgdx/gdx-pay#106]
Yesterday, some user send crach resport with this stack:
java.lang.NullPointerException: Attempt to invoke interface method 'void com.badlogic.gdx.Application.error(java.lang.String, java.lang.String, java.lang.Throwable)' on a null object reference
	at com.badlogic.gdx.utils.Logger.error(Logger.java:65)
	at com.badlogic.gdx.pay.android.googleplay.AndroidGooglePlayPurchaseManager$3.run(AndroidGooglePlayPurchaseManager.java:253)
	at java.lang.Thread.run(Thread.java:818)

**Comment by noblemaster** [comment]
That looks like an error that occurs when LibGDX is disposed/not instantiated yet unless I am reading it wrong. The reference shouldn't be 'null' as long as the app is running (not disposed). Is it possible the user closed the app while a purchase was still in progress?

**Comment by keesvandieren** [comment]
This issue has been resolved, see: #117
