### ISSUE TITLE
Gradle Error with latest snapshot

### ISSUE THREAD

**Issue by Trurl101** [libgdx/gdx-pay#108]
Since yesterday I got this error in gradle:

`Error:Module 'com.badlogicgames.gdxpay:gdx-pay-android-googleplay:0.10.0-SNAPSHOT' depends on one or more Android Libraries but is a jar`

**Comment by psiegel** [comment]
I'm seeing this too.  Is there a work-around?

**Comment by psiegel** [comment]
Figured out a work-around.  Changed my android project's dependency line from:
`compile "com.badlogicgames.gdxpay:gdx-pay-android-googleplay:$gdxPayVersion"`
to:
`compile("com.badlogicgames.gdxpay:gdx-pay-android-googleplay:$gdxPayVersion") {
        	exclude group: 'com.android.support', module: 'support-v4'
        }`

**Comment by keesvandieren** [comment]
I investigated this issue, and added Gradle instructions to the project README.md.

Instructions added to README.md:


**Configure dependencies using Gradle**

*project-root/build.gradle:*

    ext {
        gdxPayVersion = '0.10.3'
    }

*core:*

    dependencies {
        compile "com.badlogicgames.gdxpay:gdx-pay-client:$gdxPayVersion"
    }
    
*android:* 

    dependencies {
        compile "com.badlogicgames.gdxpay:gdx-pay-android:$gdxPayVersion"
        compile "com.badlogicgames.gdxpay:gdx-pay-android-googleplay:${gdxPayVersion}@aar"
    }

*ios:*
    
    dependencies {
        compile "com.badlogicgames.gdxpay:gdx-pay-iosrobovm-apple:$gdxPayVersion"
    }

Adding the '@aar' suffix to the dependency is the right way to do it.

If you still think gdx-pay is doing it wrong, feel free to open a new issue.
