### ISSUE TITLE
notifyFulfillment() is not called in PurchaseManagerAndroidAmazon

### ISSUE THREAD

**Issue by hhakobya** [libgdx/gdx-pay#109]
I'm using gdx-pay-android-openiab-0.9.2 lib for In-App Purchases for Amazon app. According to [this link](https://developer.amazon.com/public/apis/earn/in-app-purchasing/docs-v2/implementing-iap-2.0) you need to call _PurchasingService.notifyFulfillment()_ when handling consumable purchases. 

However, in [_PurchaseManagerAndroidAmazon_](https://github.com/libgdx/gdx-pay/blob/master/gdx-pay-android-amazon/src/com/badlogic/gdx/pay/android/amazon/PurchaseManagerAndroidAmazon.java) it is not called. Hence, I'm getting this error when trying to purchase consumable items in my app: 

![1](https://cloud.githubusercontent.com/assets/16702338/16267776/97799bbe-389c-11e6-9001-450f0e58344e.png)

Any ideas how to solve this issue? Thanks in advance!

**Comment by keesvandieren** [comment]
gdx-pay-android-openiab is deprecated, as the underlying openiab library is no longer maintained.

I have no Amazon device, so I am not able to help with Amazon specifics. 

Some suggestions to get it to work:

* remove the gdx-pay-android-openiab dependency
* add only gdx-pay-android-amazon
* instantiate PurchaseManagerAndroidAmazon manually, and call `PurchaseSystem.setManager()` with the instance.
* Extend PurchaseManagerAndroidAmazon with the changes you need.
* Test it locally with instructions provided in README: https://github.com/libgdx/gdx-pay#user-content-using-gdx-pay-locally-build-binaries-in-a-project

Hope this helps.

**Comment by MrStahlfelge** [comment]
This issue can be closed. OpenIAB is deprecated and current Amazon implementation fullfils all items.
