### ISSUE TITLE
Strange crashes on Google Developer Console

### ISSUE THREAD

**Issue by centy** [libgdx/gdx-pay#111]
I am receiving some strange crashes.

java.lang.SecurityException: Requires READ_PHONE_STATE: Neither user 10098 nor current process has android.permission.READ_PHONE_STATE.
	at android.os.Parcel.readException(Parcel.java:1546)
	at android.os.Parcel.readException(Parcel.java:1499)
	at com.android.vending.billing.IInAppBillingService$Stub$Proxy.getSkuDetails(IInAppBillingService.java:251)
	at org.onepf.oms.appstore.googleUtils.IabHelper.querySkuDetails(IabHelper.java:998)
	at org.onepf.oms.appstore.googleUtils.IabHelper.queryInventory(IabHelper.java:586)
	at org.onepf.oms.OpenIabHelper.queryInventory(OpenIabHelper.java:1399)
	at org.onepf.oms.OpenIabHelper$17.run(OpenIabHelper.java:1451)
	at java.lang.Thread.run(Thread.java:818)

I am using gdx-pay v0.9.2, unfortunatelly I am not sure how to reproduce that issue.

**Comment by noblemaster** [comment]
Did you add the "READ_PHONE_STATE" permission to the AndroidManifest.xml?

Also note, the Open IAB backend is deprecated (because buggy). I suggest switch to the Google Play backend.

**Comment by keesvandieren** [comment]
Use gdx-pay-android-googleplay instead.

**Comment by centy** [comment]
I need SUBSCRIPTION which is not supported by gdx-pay-android-googleplay

czw., 8.09.2016 o 14:27 użytkownik Kees van Dieren <notifications@github.com>
napisał:

**Comment by keesvandieren** [comment]
Aha. I understand. We are sorry, but I cannot help you debugging the openiab implementation (actually did that for my own app without succes, resulting in spending 2 weeks in writing gdx-pay-android-googleplay :) ).

If you have time to create a pull request for subscriptions in gdx-pay-android-googleplay, that would be really great. I am happy to help you with that.

**Comment by centy** [comment]
Hi,
It looks like I have to add this support for subscriptions, we have a lot
of crashes on old engine.  Can you guide me how to start?

pt., 9.09.2016 o 21:46 użytkownik Kees van Dieren <notifications@github.com>
napisał:

**Comment by keesvandieren** [comment]
That is great! 

To extend on this project, the following will help:

## Technologies and methodologies

* basic knowledge of gradle (e.g. run the check command)
* basic knowledge of unit-testing / tdd
* basic knowledge of the Mockito framework (current tests use Mockito 1.x)

The project is maintained using Android Studio, I never tried Eclipse so I am not sure if it is easy to extend with Eclipse.

The unit-tests are created in a Behaviour-driven development style. So each unit-test method describes an expected output for a given condition. This discussion might be useful to understand the difference between TDD and BDD: http://softwareengineering.stackexchange.com/questions/135218/what-is-the-difference-between-writing-test-cases-for-bdd-and-tdd

## Global Design

The class `PurchaseSystem` is used as entry point from the app implementing in-app purchasing.

The `PurchaseSystem` class calls the `PurchaseManager` implementation currently used, for Android this is `AndroidGooglePlayPurchaseManager`.

`AndroidGooglePlayPurchaseManager` interacts with Google Play services In-App-Billing via the class `V3GoogleInAppBillingService`, which interacts with the weak-typed error-prone Google-Play Services.

Google has a useful page worth reading: https://developer.android.com/google/play/billing/billing_subscriptions.html

**Comment by keesvandieren** [comment]
@centy have you read my previous comment with instructions to get started? Not mentioned you in that post, just need to be sure you got notified.

**Comment by centy** [comment]
Yes. Thanks
W dniu sob., 12.11.2016 o 11:08 Kees van Dieren <notifications@github.com>
napisał(a):

**Comment by centy** [comment]
Pull request was submited here: https://github.com/libgdx/gdx-pay/pull/133
