### ISSUE TITLE
handlePurchaseCanceled not called 

### ISSUE THREAD

**Issue by jsvitek** [libgdx/gdx-pay#118]
I have 2 in app products A and B. **A** is **OfferType.ENTITLEMENT** while **B** is **OfferType.CONSUMABLE.** 

Following these steps I manage not to get handlePurchaseCanceled() called on canceling purchase:
_1._ purchase product A successfully
_2._ try to purchase product B but cancel IAB purchase window (handlePurchaseCanceled is called correctly)
_3._ try to purchase product A again - handlePurchaseError is called with response code 7 "item already owned"
_4._ try to purchase product B but cancel IAB purchase window - handlePurchaseCancelled is not called anymore 

I hope I am not missing something

**Comment by keesvandieren** [comment]
We have an app (on Android and iOS) with one product: ENTITLEMENT, on which purchase cancelled are called.

Which platform / implementation are you using? For Android, gdx-pay-android-googleplay is recommended.

Maybe you can make a small github project that reproduces the issue?

**Comment by jsvitek** [comment]
Thanks for reply @keesvandieren, I forgot to mention it is an Android application that causes the issue. 
I created sample project that tries to reproduce the issue. It works 100% times for me. 
Basically I just followed [Integration example with resolvers](https://github.com/libgdx/gdx-pay/wiki/Integration-example-with-resolvers) tutorial and added two buttons for purchasing ENTITLEMENT and CONSUMABLE and a text area for messages. Please run the app on Android and follow steps I mentioned above. 

Here is the [link for the project](https://github.com/jsvitek/gdx_pay_issue118)

Also I am using both gdx-pay-android.jar and gdx-pay-android-googleplay.jar I am not sure whether to use both but in the gdx pay readme file it is said to use both of them.

**Comment by keesvandieren** [comment]
Thanks for creating a reproduction project!

I reproduced the bug, and pushed a fix to master. It needs to be unit-tested and verified better before releasing it, which I can do later (hopefully next week).

You can test it within your own project, by cloning gdx-pay, installing it in your local Maven repo and setting the version number of gdx-pay dependencies to 0.11.1-SNAPSHOT (procedure is described here:  user-content-using-gdx-pay-locally-build-binaries-in-a-project )

**Comment by keesvandieren** [comment]
Solved in v0.10.3
