### ISSUE TITLE
 Error:Module 'com.badlogicgames.gdxpay:gdx-pay-android-googleplay:0.10.3' depends on one or more Android Libraries but is a jar.

### ISSUE THREAD

**Issue by abhishekraisharma** [libgdx/gdx-pay#124]
Hi,

I am using the configuration suggested but Kees Van Dieren.
for my android project.

dependencies {
compile "com.badlogicgames.gdxpay:gdx-pay-client:${gdxPayVersion}"
compile "com.badlogicgames.gdxpay:gdx-pay-android:${gdxPayVersion}"
compile "com.badlogicgames.gdxpay:gdx-pay-android-googleplay:${gdxPayVersion}"
}

But getting this error.

Error:Module 'com.badlogicgames.gdxpay:gdx-pay-android-googleplay:0.10.3' depends on one or more Android Libraries but is a jar.

Kindly help.

**Comment by piotrros** [comment]
Huh, same problem here, just wanted to create a topic.

**Comment by keesvandieren** [comment]
I investigated this issue, and added Gradle instructions to the project README.md.

Instructions added to README.md:


**Configure dependencies using Gradle**

*project-root/build.gradle:*

    ext {
        gdxPayVersion = '0.10.3'
    }

*core:*

    dependencies {
        compile "com.badlogicgames.gdxpay:gdx-pay-client:$gdxPayVersion"
    }
    
*android:* 

    dependencies {
        compile "com.badlogicgames.gdxpay:gdx-pay-android:$gdxPayVersion"
        compile "com.badlogicgames.gdxpay:gdx-pay-android-googleplay:${gdxPayVersion}@aar"
    }

*ios:*
    
    dependencies {
        compile "com.badlogicgames.gdxpay:gdx-pay-iosrobovm-apple:$gdxPayVersion"
    }

Adding the '@aar' suffix to the dependency is the right way to do it.

If you still think gdx-pay is doing it wrong, feel free to open a new issue.
