### ISSUE TITLE
Vulnerability issue showing up on Developer Console

### ISSUE THREAD

**Issue by DavidBVal** [libgdx/gdx-pay#125]
this [vulnerability warning](https://support.google.com/faqs/answer/7054270) showed up today on Google Play Console.

Excerpt:

> If your app is invoking the In-app billing service without setting a target package for the intent. This can enable a malicious package to bypass the Play store billing system and access items that have not been purchased.
> 
> Steps to fix:
> 
> 1. If you are using IabHelper, please start using the latest SDK. 
> 2. If you are manually invoking the In-app billing service, please ensure that you are calling Intent.setPackage(“com.android.vending”) on any intents to "com.android.vending.billing.InAppBillingService.BIND".
> 3. Sign in to your Developer Console and submit the updated version of your app.

I am using a pretty standard gdx-pay implementation, gdx-pay 0.10.0, everything working fine, but I wonder if this is a real issue, as the library handles all the IAB calls for me...

**Comment by keesvandieren** [comment]
I will look into this tomorrow.

**Comment by jstuyts** [comment]
This has been correctly implemented since January 9: https://github.com/libgdx/gdx-pay/commit/c939b2d8f1a859a0cdee3378586eb5de96bb4067#diff-42b47e4d776ee81175374ba8e0340111R84

Could you provide details about how you invoke gdx-pay?

**Comment by DavidBVal** [comment]
I use the 0.10.0 jars directly added as libraries, not with gradle (gdx-pay-client-0.10.0.jar, gdx-pay-android-googleplay-0.10.0.jar).

On my Game class I have:

```

//constructor
public myGame(){

	// ---- IAP: define products ---------------------
	purchaseManagerConfig = new PurchaseManagerConfig();	    	    
	purchaseManagerConfig.addOffer(new Offer().setType(OfferType.ENTITLEMENT).setIdentifier(ID_FULL_LICENSE));
	...
}


public PurchaseObserver purchaseObserver = new PurchaseObserver() {

	    @Override
	    public void handleRestore (Transaction[] transactions) {
	        for (int i = 0; i < transactions.length; i++) 
	            if (checkTransaction(transactions[i].getIdentifier()) == true){
	            	//.. do stuff
	            	break;	            
	             }
	    }

	    @Override
	    public void handleRestoreError (Throwable e) {   }

	    @Override
	    public void handleInstall () {  }

	    @Override
	    public void handleInstallError (Throwable e) {    }

	    @Override
	    public void handlePurchase (Transaction transaction) {
	        checkTransaction(transaction.getIdentifier());
	        //.. do stuff 
	    }

	    @Override
	    public void handlePurchaseError (Throwable e) {    }

	    @Override
	    public void handlePurchaseCanceled () {    }
	};
	
	protected boolean checkTransaction (String ID) {
	    boolean returnbool = false;
	    if (ID_FULL_LICENSE.equals(ID)) {	    	
	    	//activate license here	    	
	        returnbool = true;
	    }
	    	    
	    return returnbool;
	}

```

Purchase resolver class:

```
public abstract class PurchaseResolver {

	protected PurchaseManager mgr;
	public PurchaseResolver () {    }

	public void initializeIAP (PurchaseManager mgr, PurchaseObserver purchaseObserver, PurchaseManagerConfig config) {
    		this.mgr = mgr;
    		
    		if (mgr != null) {			// set and install the manager manually
        		PurchaseSystem.setManager(mgr);
        		PurchaseSystem.install(purchaseObserver, config);
    		} else {
      			if (PurchaseSystem.hasManager()) { // install and get the manager automatically via reflection
            			this.mgr = PurchaseSystem.getManager();            
            			PurchaseSystem.install(purchaseObserver, config); // install the observer
        		}
    		}
	}

	public void requestPurchase (String productString) {
    		if (mgr != null) 
        		PurchaseSystem.purchase(productString);
	}

	public void requestPurchaseRestore () {
    		try {			
		 	if (mgr != null) 
		        	PurchaseSystem.purchaseRestore();					
		} catch (final Exception ex) {	}   
	}

	public PurchaseManager getPurchaseManager () {
    		return mgr;
	}
}
```

my Android resolver, which extends the PurchaseResolver above adding Google Play Store initialization:
```
public class AndroidResolver extends PurchaseResolver {

	public AndroidResolver(MyGame mygame, AndroidApplication androidApplication) {
	    super();
	    this.mygame = mygame;
	    this.androidApplication = androidApplication;    
    
	    PurchaseManagerConfig config = mygame.purchaseManagerConfig;
	    config.addStoreParam(PurchaseManagerConfig.STORE_NAME_ANDROID_GOOGLE,GOOGLEKEY);    
	    initializeIAP(null, mygame.purchaseObserver, config);    
	}
}
```

I assign the resolver to my game class with a setPurchaseResolver method after creating it.

I call purchases  with 

MyGame.getPurchaseResolver().requestPurchase(MyGame.ID_TEST_LICENSE);

**Comment by DavidBVal** [comment]
I just noticed the popup telling me about the vulnerability also tells me the culprit classes:

Vulnerable classes:
com.google.android.gms.internal.cs
com.google.android.gms.internal.cu
com.google.android.gms.internal.cw

the names are ofuscated, of course... I'll have to upload a build that excluded those classes from ofuscation.

**Comment by DavidBVal** [comment]
Issue solved, and gdx-pay was not related to it. Believe it or not, google-play-services-lib revision 19 is the culprit, and updating the library fixed the problem and removed the warning.
