### ISSUE TITLE
Android Failed to Bind to Service (Again)

### ISSUE THREAD

**Issue by fat2019** [libgdx/gdx-pay#129]
But this time not on start. I open the game, then click "rate" button and play store opens. When I close play store, game crashes. In the method

```
   public void handleInstallError (Throwable e) {
        Gdx.app.log("ERROR", "PurchaseObserver: handleInstallError!: " + e.getMessage());
        throw new GdxRuntimeException(e);
    }
```

I've just commented out the line throw new GdxRuntimeException(e); and now it doesn't kick me out of the application which works ok for me. The throw new GdxRuntimeException(e); is making the application to completely stop working so it might be a good idea to be fixed.

**Comment by keesvandieren** [comment]
In handleInstallError, you should not throw an Exception.

I know a few situations wherein this can happen:

* Countries not yet eligible for in-app purchases. More here: https://support.google.com/googleplay/android-developer/table/3541286?hl=en
* Apps installed via alternative app-stores, that do not support Google In-App billing.

In our case, we report 'handleInstallErrors' to our tracking system, to see which users install our free app but have no access to in-app purchases.

**Comment by keesvandieren** [comment]
It is legitimate that handleInstallError is called; do not throw an exception when it is called, log it to Crash reporter or something like that.
