### ISSUE TITLE
iOS MOE transaction data is null

### ISSUE THREAD

**Issue by la-matthew-yang** [libgdx/gdx-pay#135]
In PurchaseManageriOSApple line 291, payment.requestData() seems to always return null when running with MOE on iOS devices.

Purchase is successful.

**Comment by maitl** [comment]
Same here

**Comment by keesvandieren** [comment]
Maybe @liliomk can have a look at this?

**Comment by keesvandieren** [comment]
We are not gdx-pay with MOE a.t.m. So bugfix has to come from the community. If anyone is willing to dive into it and resolve it, we are willing to accept PRs.

**Comment by MrStahlfelge** [comment]
Closing this because ios-moe won't be used by any new projects any more.
