### ISSUE TITLE
Question: why does PurchaseObserver.handleRestore have a break in example code?

### ISSUE THREAD

**Issue by codeulike** [libgdx/gdx-pay#136]
Hi just a quick question, re the 'example with resolvers' here:
https://github.com/libgdx/gdx-pay/wiki/Integration-example-with-resolvers

The example PurchaseObserver.handleRestore loops through transactions but it breaks out of the loop if checkTransaction returns true. Why is that? Wont that mean skipping over the other transactions?

Regards

**Comment by MrStahlfelge** [comment]
Probably the example project this code was used from just had a single entitlement IAP.

The example will be removed soon and replaced by another one.
