### ISSUE TITLE
No purchase manager found IN LIVE WALLPAPER

### ISSUE THREAD

**Issue by klaszlo8207** [libgdx/gdx-pay#139]
I used this code

https://github.com/libgdx/gdx-pay/blob/master/gdx-pay-tests/src/com/badlogic/gdx/pay/tests/PayTest.java

It is always say that:

"- no purchase manager found"

What does it mean?

**Comment by itsabhiaryan** [comment]
On which platform you're running PayTest Application.

**Comment by klaszlo8207** [comment]
Hello,

here is my dependencies:

dependencies {
    compile files('libs/gdx.jar')
    compile files('libs/gdx-backend-android.jar')
    compile files('libs/gdx-freetype.jar')
    compile files('libs/gdx-bullet.jar')
    compile 'com.github.yukuku:ambilwarna:2.0.1'

    compile files('libs/gdx-pay-android-0.10.3-library.jar')
    compile files('libs/gdx-pay-android-googleplay-0.10.3.jar')
    compile files('libs/gdx-pay-0.10.3-library.jar')
    compile files('libs/gdx-pay-client-0.10.3-library.jar')
}

It is for android. I justr copy pasted the dependencies and then the example project's code on my android live wallpaper.

**Comment by klaszlo8207** [comment]
I updated to gradle build:


configurations { natives }

```
dependencies {
    /*
    compile files('libs/gdx.jar')
    compile files('libs/gdx-backend-android.jar')
    compile files('libs/gdx-freetype.jar')
    */
    compile "com.badlogicgames.gdx:gdx:$gdxVersion"

    compile "com.badlogicgames.gdx:gdx-backend-android:$gdxVersion"
    natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-armeabi"
    natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-armeabi-v7a"
    natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-arm64-v8a"
    natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-x86"
    natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-x86_64"
    compile "com.badlogicgames.gdx:gdx-freetype:$gdxVersion"
    natives "com.badlogicgames.gdx:gdx-freetype-platform:$gdxVersion:natives-armeabi"
    natives "com.badlogicgames.gdx:gdx-freetype-platform:$gdxVersion:natives-armeabi-v7a"
    natives "com.badlogicgames.gdx:gdx-freetype-platform:$gdxVersion:natives-arm64-v8a"
    natives "com.badlogicgames.gdx:gdx-freetype-platform:$gdxVersion:natives-x86"
    natives "com.badlogicgames.gdx:gdx-freetype-platform:$gdxVersion:natives-x86_64"

    compile "com.badlogicgames.gdxpay:gdx-pay-client:$gdxPayVersion"
    compile "com.badlogicgames.gdxpay:gdx-pay-android:$gdxPayVersion"
    compile "com.badlogicgames.gdxpay:gdx-pay-android-googleplay:${gdxPayVersion}@aar"

    /*
    compile files('libs/gdx-pay-android-0.10.3-library.jar')
    compile files('libs/gdx-pay-android-googleplay-0.10.3.jar')
    compile files('libs/gdx-pay-0.10.3-library.jar')
    compile files('libs/gdx-pay-client-0.10.3-library.jar')
    */
    compile 'com.github.yukuku:ambilwarna:2.0.1'
}


// called every time gradle gets executed, takes the native dependencies of
// the natives configuration, and extracts them to the proper libs/ folders
// so they get packed with the APK.
task copyAndroidNatives() {
    file("libs/armeabi/").mkdirs();
    file("libs/armeabi-v7a/").mkdirs();
    file("libs/arm64-v8a/").mkdirs();
    file("libs/x86_64/").mkdirs();
    file("libs/x86/").mkdirs();

    configurations.natives.files.each { jar ->
        def outputDir = null
        if(jar.name.endsWith("natives-arm64-v8a.jar")) outputDir = file("libs/arm64-v8a")
        if(jar.name.endsWith("natives-armeabi-v7a.jar")) outputDir = file("libs/armeabi-v7a")
        if(jar.name.endsWith("natives-armeabi.jar")) outputDir = file("libs/armeabi")
        if(jar.name.endsWith("natives-x86_64.jar")) outputDir = file("libs/x86_64")
        if(jar.name.endsWith("natives-x86.jar")) outputDir = file("libs/x86")
        if(outputDir != null) {
            copy {
                from zipTree(jar)
                into outputDir
                include "*.so"
            }
        }
    }
}

task run(type: Exec) {
    def path
    def localProperties = project.file("../local.properties")
    if (localProperties.exists()) {
        Properties properties = new Properties()
        localProperties.withInputStream { instr ->
            properties.load(instr)
        }
        def sdkDir = properties.getProperty('sdk.dir')
        if (sdkDir) {
            path = sdkDir
        } else {
            path = "$System.env.ANDROID_HOME"
        }
    } else {
        path = "$System.env.ANDROID_HOME"
    }

    def adb = path + "/platform-tools/adb"
    commandLine "$adb", 'shell', 'am', 'start', '-n', 'com.mygdx.game/com.mygdx.game.AndroidLauncher'
}
```


THE SAME ERROR!

**Comment by klaszlo8207** [comment]
Some News:

**IAP: Error creating IAP for Android.
                                               java.lang.RuntimeException: Can't find your gdx activity to instantiate Android IAP. Looks like you have implemented AndroidApplication without using Activity or Fragment classes or Activity is not available at the moment**

**Comment by itsabhiaryan** [comment]
Use
`-dontwarn com.badlogic.gdx.pay.**` instead of `-dontwarn com.badlogic.gdx.pay**`

**Comment by klaszlo8207** [comment]
Thanks but please read my previous comment. Is it working in LWP or not? I think it is only for Activities.

**Comment by klaszlo8207** [comment]
the probleme is here:

https://github.com/libgdx/gdx-pay/blob/master/gdx-pay-android/src/com/badlogic/gdx/pay/android/IAP.java

line 87

if (activity == null) {
				throw new RuntimeException("Can't find your gdx activity to instantiate Android IAP. "
					+ "Looks like you have implemented AndroidApplication without using "
					+ "Activity or Fragment classes or Activity is not available at the moment");
}

I think this is a BUG. I tried to add in a Live Wallpaper Settings Activity (PreferenceActivity) but the same error :(

**IAP: Error creating IAP for Android.
java.lang.RuntimeException: Can't find your gdx activity to instantiate Android IAP. Looks like you have implemented AndroidApplication without using Activity or Fragment classes or Activity is not available at the moment**

**Comment by klaszlo8207** [comment]
The FIX is:

else if (Gdx.app instanceof com.badlogic.gdx.backends.android.AndroidLiveWallpaper) {
				activity = ...;
}

Can somebodey fix this for live wallpapers?

**Comment by klaszlo8207** [comment]
**OK I returned to the 'com.anjlab.android.iab.v3:library:1.0.+'**

Anyway please someone fix the library later, Thanks

**Comment by keesvandieren** [comment]
Hi,

Have never created a wallpaper app in Android.

Does a Wallpaper app have an Activity?

Does you app have to support for platforms other than Google Play?

**Comment by klaszlo8207** [comment]
No, dont have an activity, the solution is the code I just posted yesterday. AndI only use this for Play. I have only Settings Activity. (PrefereneActivity) Please do an update if you can. Anyway I have no time for this, I using this library:  'com.anjlab.android.iab.v3:library:1.0.+'

And work like a charm

**Comment by keesvandieren** [comment]
It is much more work than you suggest. 

We contributed two weeks of our time to rewrite the Android implementation (e.g. we added gdx-pay-android-googleplay).

Adding support for live-wall-paper takes 2 or 3 days.

We accept and review pull requests (for free). If someone wants to hire us to add support for live wall-paper apps, feel free to contact us via info@squins.com

**Comment by keesvandieren** [comment]
There are no plans to built in support for wallpapers.

If anyone wants to contribute it we are waiting for PR.
