### ISSUE TITLE
Cannot get Information on GooglePlayStore if there are more than 20 Offers

### ISSUE THREAD

**Issue by lozan** [libgdx/gdx-pay#144]
The current implementation of fetchSkuDetails() in V3GoogleInAppBillingService does not handle a scenario in which there are more than 20 products and it throws an exception in executeGetSkuDetails().

The reason for that is the limit in getSkuDetails(), which allows max 20 SKUs to be passed in.

In order for the implementation to handle more, the list of products passed in fetchSkuDetails should be split in chunks of max 20 items and executeGetSkuDetails should be called on each chunk separately.

**Comment by keesvandieren** [comment]
Just released 0.11.0. Should be available in Maven Central shortly
