### ISSUE TITLE
Re-purchase of entitlement results in Response Code 3

### ISSUE THREAD

**Issue by activegamedev** [libgdx/gdx-pay#149]
From what I understand Google no longer saves test purchases, so there is no way to cancel them from the Payment Center. When I try and re-purchase an Entitlement, I get a Response Code 3:  This billing API version is not supported for the type requested. Shouldn't I receive a pop-up stating I already own the item? This occurs regardless of the Google Play account used, as long as the account is linked to the device that I made the test purchase on. If I remove that account everything works again.

I tried using this, but it didn't work:
`PurchaseManager mananager = PurchaseSystem.getManager();
if (manager instanceof PurchaseManagerTestSupport) {
    ((PurchaseManagerTestSupport) manager).cancelTestPurchases();
}`

**Comment by keesvandieren** [comment]
Are you using `gdx-pay-android-googleplay` or` gdx-pay-android-openiab`?

**Comment by gamedev263** [comment]
I am using gdx-pay-android-googleplay, the same code as in the wiki with the obvious changes. Currently I work around it by setting the offer as a consumable. I noticed that:  <if(manager instanceof PurchaseManagerTestSupport)> always returns false (according to Android Studio). So their also needs to be a better way to remove test purchases (Google support recommended just consuming it), although I'm not sure why no pop-up appears stating I own the item, it just throws the handlePurchaseError.

**Comment by keesvandieren** [comment]
What is the output of:

`System.out.println("Purchase Manager class:  "+ manager.getClass().getName());`

**Comment by gamedev263** [comment]
com.badlogic.gdx.pay.android.googleplay.AndroidGooglePlayPurchaseManager

**Comment by keesvandieren** [comment]
Which version of gdx-pay are you using?

Op 7 jun. 2017 01:51 schreef "Matt" <notifications@github.com>:

**Comment by gamedev263** [comment]
I am using gdx-pay 0.11.1 on all submodules. Maybe I should also note I am using the latest version of Android Studio 3.0, I'll try testing it out again.

**Comment by gemorg** [comment]
I have the same problem.

- libgdx 1.9.6
- gdx-pay 0.11.1
- Android Studio 2.2

**Comment by JKazma** [comment]
Any news on this? I also get the RESULT_BILLING_UNAVAILABLE = 3 response when I try to purchase an entitlment that was already purchased instead of getting the correct RESULT_ITEM_ALREADY_OWNED = 7 response. I use gdx-pay 0.11.2

**Comment by MrStahlfelge** [comment]
Hi, when having problems, please try if your problem is solved by using googlebilling.
