### ISSUE TITLE
"Integration example with resolvers"  constructors aren't coherent

### ISSUE THREAD

**Issue by fmmarzoa** [libgdx/gdx-pay#151]
This document:

https://github.com/libgdx/gdx-pay/wiki/Integration-example-with-resolvers

Creates a base abstract class which only constructor is as follows:

```
public abstract class PlatformResolver {
...
    public PlatformResolver () { 	}

```
That's, no code, no arguments. The real issue is the lack of arguments, because just one step further, when it starts derivating such abstract class to create the platform-specific resolver, it tries to call that constructor using one argument. Let's take the Android example:

```
public class AndroidResolver extends PlatformResolver {
...
    public AndroidResolver(Tanks tanks, AndroidApplication androidApplication) {
         super(tanks);
...

```
So either the PlatformResolver constructor should take one argument, or the AndroidResolver (and other specific resolvers) should not be calling super(tanks).

**Comment by MrStahlfelge** [comment]
The page will get removed soon and an example project will be provided, see #104
