### ISSUE TITLE
"Integration example with resolvers" broken link

### ISSUE THREAD

**Issue by fmmarzoa** [libgdx/gdx-pay#152]
On this document:
https://github.com/libgdx/gdx-pay/wiki/Integration-example-with-resolvers

The link referenced here is broken (404):

> the getters and setters for the plaformResolver belong to you main game class. check here: https://bitbucket.org/just4phil/gdxpayexample/src/b86dd21d2a06da477c78f2e911d189d69b393890/core/src/com/mygdx/game/GdxPayExample.java?at=master

**Comment by just4phil** [comment]
Hmm...
Should be this

https://bitbucket.org/just4phil/gdxpayexample/src/bb586690e7121c04809d0b4440a28ed75f170569/core/src/com/mygdx/game/GdxPayExample.java?at=master&fileviewer=file-view-default

**Comment by keesvandieren** [comment]
The example is outdated: old Robovm version, old gdx-pay version. Anybody willing the example?

**Comment by MrStahlfelge** [comment]
See #104, this will get solved with a working example project.
