### ISSUE TITLE
ios gdx-pay NAT64 network support

### ISSUE THREAD

**Issue by gemorg** [libgdx/gdx-pay#153]
I'm using gdx-pay in my libgdx application and apple rejected my application because they can't take a purchase when device connected to ipv6-only wi-fi.

I'm using:
- gradle
- latest libgdx 1.9.6
- latest robopods 1.14.0
- latest gdx-pay 0.11.1
- robovm 2.3.1

I was find [this](https://github.com/libgdx/gdx-pay/issues/126) closed issue. But I did not understand how to solve this problem.

**Comment by noblemaster** [comment]
This is not related to gdx-pay. You need to connect to a DNS address, not IPv4 address.

Wrong (won't work over IPv6): 102.3.0.137
Correct: myserver.domain.com
