### ISSUE TITLE
Gdx-pay iOS Robovm crash

### ISSUE THREAD

**Issue by keesvandieren** [libgdx/gdx-pay#158]
Sometimes we have this crash on iOS apps: https://pastebin.com/G9FB52DW

"
Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x2212002d005c05ab
 "

Relevant parts of discussion on Robovm Gitter chat:

I might have found it. addStrongRef should be used when setting / adding a Delegate / Observer / Event Listener whose property / setter name is not delegate / setDelegate.

According to this Google group post: https://groups.google.com/forum/#!topic/robovm/fHLriJ2_j5Y

Gdx-pay adds an observer here: https://github.com/libgdx/gdx-pay/blob/master/gdx-pay-iosrobovm-apple/src/main/java/com/badlogic/gdx/pay/ios/apple/PurchaseManageriOSApple.java#L322

So on line 323 we should add:

defaultQueue.addStrongRef(appleObserver);

And line 142 (in dispose() method) we should update like so:

        SKPaymentQueue defaultQueue = SKPaymentQueue.getDefaultQueue();
        defaultQueue.removeTransactionObserver(appleObserver);
        defaultQueue.removeStrongRef(appleObserver);

**Comment by keesvandieren** [comment]
Released 0.11.2 which has this fix.

**Comment by balepc** [comment]
I still had this issue with 0.11.2 - https://pastebin.com/PkvvMHAA

**Comment by keesvandieren** [comment]
Based on this stack-trace, it is impossible to decide whether it is caused by gdx-pay or not. 

Why do you think its gdx-pay? Any more concrete pointers?

Our apps no longer do have this problem after 0.11.2

**Comment by balepc** [comment]
If I remove gdx-pay it doesn't crash any more. What kind of logs I could provide?

**Comment by keesvandieren** [comment]
Can you reproduce the crash? If that is true, can you submit a minimal app that produces the issue?
