### ISSUE TITLE
Request for input: remove unused modules, code cleanup

### ISSUE THREAD

**Issue by keesvandieren** [libgdx/gdx-pay#159]
We have some dummy implementations that are actually not implemented.

Additionally, some of the implementations are based on unmaintained third party frameworks, are partially implemented or are made for hardware which is discontinued.

Can we get rid of them?

Proposal:

* Remove empty modules: gdx-pay-desktop-apple, gdx-pay-gwt-googlewallet
* Remove all empty implementations in gdx-pay-server: PurchaseVerifierAndroidGoogle, PurchaseVerifierAndroidAmazon.java
* Remove incomplete / probably unused modules: gdx-pay-android-openiab, gdx-pay-android-ouya, gdx-pay-android-amazon
* Cleanup, do some breaking changes to improve maintainability.
* Improve docs of remaining modules.

Questions:
* Is anyone using the modules that are mentioned in this issue?
* Any further suggestions to improve the quality?
* Anybody willing to help?

**Comment by noblemaster** [comment]
I agree that removing incomplete/empty parts probably makes sense.

Re-breaking changes to improve maintainability: I'd be careful with breaking changes. What did you have in mind?

**Comment by keesvandieren** [comment]
Removing incomplete / empty parts: 

* We should remove  gdx-pay-desktop-apple, gdx-pay-gwt-googlewallet. I will do that in future.
* Modules: gdx-pay-android-openiab, gdx-pay-android-ouya, gdx-pay-android-amazon might have some users. Do you agree to remove them as wel?

About breaking changes:  one of the breaking changes I have in mind, is to get rid of static instances and static method calls.

For example, make PurchaseSystem an object, and call methods on that object instead of static methods on PurchaseSystem.

Static data in Android apps are hardly done right, often they cause problems with pause / resume actions of Android apps. A few bugs related to that where fixed in Gdx-pay.

Our personal preference also is to have Immutable domain objects. Classes like Information, Offer and Transaction could for example become immutable. This improves clarity and reduces bugs in future changes.

Internally, we do all of our projects in Kotlin. Maybe we should just create a fork of gdx-pay and rewrite it in Kotlin. What do you think about that?

**Comment by noblemaster** [comment]
> We should remove gdx-pay-desktop-apple, gdx-pay-gwt-googlewallet. I will do that in future.

Makes sense, given they are not implemented at all.

> Modules: gdx-pay-android-openiab, gdx-pay-android-ouya, gdx-pay-android-amazon might have some users. Do you agree to remove them as well?

I wonder? Probably makes sense to remove OpenIAB as it isn't quite working right and we have alternatives? OUYA & Amazon on the other hand are working for the most part, no? 

> About breaking changes: one of the breaking changes I have in mind, is to get rid of static instances and static method calls. For example, make PurchaseSystem an object, and call methods on that object instead of static methods on PurchaseSystem.

Good point. Indeed, static variables aren't working very well on Android. The goal was to have PurchaseSystem auto-detect the jars/market and then auto-setup the manager. I guess we should probably remove it altogether as it doesn't really make make sense otherwise?

> Our personal preference also is to have Immutable domain objects. Classes like Information, Offer and Transaction could for example become immutable. 

That make sense. Those objects are simple enough to make them immutable!

> Internally, we do all of our projects in Kotlin. Maybe we should just create a fork of gdx-pay and rewrite it in Kotlin. What do you think about that?

Given the user & developer base for gdx-pay isn't big, having an additional Kotlin version seems to make development of gdx-pay even slower. It's possible to call Java from Kotlin, but not the other way around. Anyhow, if you have time to create a fork, I can't really stop you :)

**Comment by thorthur** [comment]
gdx-pay-android-amazon has at least one user right now.
Implementation is mostly functional considering PR #161.

Considering the other points, I of course agree this library would benefit from additional love and cleanup.

**Comment by MrStahlfelge** [comment]
I would suggest the following improvements for the next release:

* Delete Ouya, OpenIAB, apple, googlewallet
* Deprecate PurchaseSystem

Revise main readme file: 
* Strip manual configuration (whoever wants to configure manually should know what to do)
* Split AndroidManifest, Proguardconfig to the entries that are needed for the whole project and for certain implementations
* Remove explanation of PurchaseSystem, but encourage to instantiate the PurchaseManager within the project launcher classes, explain all steps how to make a simple purchase
* Remove release history, this belongs to the releases tab

**Comment by MrStahlfelge** [comment]
And by the way, can you add issue labels for the implementations and platforms so we can label issues to the implementations causing the problem?
See here for an example: https://github.com/MrStahlfelge/gdx-gamesvcs/issues?q=is%3Aopen+is%3Aissue

**Comment by keesvandieren** [comment]
Thanks for input @MrStahlfelge 

Did some of the removals I proposed earlier.

So far I got no reaction on removal of `gdx-pay-server`. Anybody using it? Someone tried to use it according to #167 .

@MrStahlfelge you asked to remove `Apple`. We are still using it (not subscriptions, only one-time In-App purchases, and it works well for our apps).

I agree with your other changes. Regarding to removing manual setup: @noblemaster was still using it, at least one year ago ;-).

**Comment by MrStahlfelge** [comment]
I was referring to desktop-apple which is gone now. :-)

Great to here that you agree on my thoughts regarding the readme file. If you want, I can work on the readme file on my fork.

**Comment by MrStahlfelge** [comment]
I doubt anybody uses the server component. It is four years old and undocumented...

**Comment by keesvandieren** [comment]
@MrStahlfelge added labels to a few issues. Does this help you?

Feel free to improve the docs as you proposed. There are some requests for (explanation of) examples, so if you create an even more simple example without PurchaseSystem it would be really great, than we can close that issues as well.

**Comment by MrStahlfelge** [comment]
I've added a PR with the new readme files.

With the labels, I think it would be good to have labels for each implementation. We have three "android" implementations which all will get the "android" label. Filtering does not show only the issues of interest then.

**Comment by MrStahlfelge** [comment]
The only thing left to do here is deprecation PurchaseSystem / IAP (Android) classes. Will be done after example project without using it is released. (#104)

**Comment by MrStahlfelge** [comment]
This is done.
