### ISSUE TITLE
Amazon Fire TV not recognized during reflection?

### ISSUE THREAD

**Issue by just4phil** [libgdx/gdx-pay#16]
Hi @noblemaster 
if i use gdx-pay regularly on my amazon fire tv i always get a purchasemanager == null.
after investigation i found out:

gdxClazz = com.badlogic.gdx.Gdx
gdxLifecycleListenerClazz = com.badlogic.gdx.LifecycleListener
gdxAppObject = null !!! => Object gdxAppObject = gdxClazz.getField("app").get(null);
gdxAppLogMethod => fails because gdxAppObject == null => catch error

with deactivated purchasesystem all is running fine!

what can be the problem?
bye
phil

**Comment by just4phil** [comment]
@noblemaster 
here is the stacktrace (see below)

the app starts with the correct amazon iap purchase manager
but somehow it gets lost (maybe after pause/resume?... lost statics??) and then the reflection code seems to set the openIAB manager(?) in purchaseRestore() via PurchaseSystem.hasManager()

i only dispose the manager after a purchase and in onDestroy() .... i dont do anything in pause/resume.

i see only 7 crashes in purchase()
but i see 312 crashes in purchaseRestore()

this sucks and confuses me :)

java.lang.NullPointerException
    at com.badlogic.gdx.pay.android.openiab.PurchaseManagerAndroidOpenIAB.purchaseRestore(PurchaseManagerAndroidOpenIAB.java:323)
    at com.badlogic.gdx.pay.PurchaseSystem.purchaseRestore(PurchaseSystem.java:188)
    at de.philweb.philengine.common.PlatformResolver.requestPurchaseRestore(PlatformResolver.java:42)
    at de.philweb.game2.screens.LoadingAsyncScreen.(LoadingAsyncScreen.java:112)
    at de.philweb.game2.common.Tanks.getStartScreen(Tanks.java:174)
    at de.philweb.philengine.common.Game.create(Game.java:277)
    at de.philweb.game2.common.Tanks.create(Tanks.java:133)
    at com.badlogic.gdx.backends.android.AndroidGraphics.onSurfaceChanged(AndroidGraphics.java:237)
    at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1505)
    at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)

**Comment by noblemaster** [comment]
Looks like the helper is null!? The system is either not initialized (yet) or already disposed. Did you put some log messages in to check if the helper is instantiated etc.?

**Comment by just4phil** [comment]
well .... PurchaseManagerAndroidOpenIAB should never be called because its the amazon platform!!

**Comment by just4phil** [comment]
@noblemaster 
hi chris!
i still have a serious problem (with the reflection stuff?)
i still get crash reports from my amazon fire tv app, where NO(!!!) openIAB purch.mgr. should be used!
i get a nullpointer in your new refreshSKUs(): java.lang.NullPointerException	PurchaseManagerAndroidOpenIAB.java:159
for (int i = 0; i < config.getOfferCount(); i++) {

what makes me nervous is that there shouldnt be a PurchaseManagerAndroidOpenIAB!!!!!
the fire tv app can only bind PurchaseManagerAndroidAmazon!!
so why is there sometimes the PurchaseManagerAndroidOpenIAB bound??

this means  that some people cant buy my app and that a bad thing ;)
bye
phil

**Comment by noblemaster** [comment]
I check your code & found the following: https://github.com/libgdx/gdx-pay/blob/master/gdx-pay-android-amazon/src/com/badlogic/gdx/pay/android/amazon/PurchaseManagerAndroidAmazon.java#L213

Don't call PurchaseSystem in your custom Amazon purchase manager. That code will instantiate the OpenIAB purchase manager via reflection...

**Comment by just4phil** [comment]
thx!! 
i saw that too and asked myself where this is used...
i will change that
thanks!!!!

**Comment by just4phil** [comment]
hast du google hangouts?

**Comment by just4phil** [comment]
@noblemaster
Just received  the next crash report about openIAB mgr in my amazon fire TV game....from the New Version where i disabled the Call to hasManager()

That sucks!

What am i doing wrong??

I dont like the automatic reflection stuff! 
The user should have full control over what is happening!
How can i fully disable the reflection stuff?? We should at least offer a method to disable it and let the user control it manually without those side effects...

**Comment by noblemaster** [comment]
You probably have some other places where you use "PurchaseSystem". Given that you don't use reflection, do a search in your code for "PurchaseSystem" and removed it. Also, Search for "IAP" which does reflection for the Android backend. Please make sure to add the onActivityResult listener though.

A cleaner option would be to update IAP.java and add reflection code for Amazon Fire TV; i.e. if you are on Amazon Fire TV, make it to use your custom Amazon backend and prevent instantiation of OpenIAB.

Sorry, hardly using Google Hangouts at all!

**Comment by UrbanKristan** [comment]
I'm not really sure I have any business posting here, but I seem to also be getting this error with very simple code. Am I missing something?

purchaseManagerConfig = new PurchaseManagerConfig();
			purchaseManagerConfig.addStoreParam(PurchaseManagerConfig.STORE_NAME_ANDROID_AMAZON, "");
purchaseManagerConfig.addOffer(new Offer().setType(OfferType.ENTITLEMENT).setIdentifier(ProductLibrary.DISABLE_ADS));
purchaseManagerConfig.addOffer(new Offer().setType(OfferType.CONSUMABLE).setIdentifier(ProductLibrary.SMALL_HINT_PACK));
purchaseManagerConfig.addOffer(new Offer().setType(OfferType.CONSUMABLE).setIdentifier(ProductLibrary.MEDIUM_HINT_PACK));
purchaseManagerConfig.addOffer(new Offer().setType(OfferType.CONSUMABLE).setIdentifier(ProductLibrary.BIG_HINT_PACK));

PurchaseSystem.install(purchaseObserver, purchaseManagerConfig);

________________________________________________________

08-02 18:16:39.087 10613 10639 E AndroidRuntime: java.lang.NullPointerException
08-02 18:16:39.087 10613 10639 E AndroidRuntime: 	at com.badlogic.gdx.pay.android.openiab.PurchaseManagerAndroidOpenIAB.refreshSKUs(PurchaseManagerAndroidOpenIAB.java:159)
08-02 18:16:39.087 10613 10639 E AndroidRuntime: 	at com.badlogic.gdx.pay.android.openiab.PurchaseManagerAndroidOpenIAB.purchase(PurchaseManagerAndroidOpenIAB.java:287)
08-02 18:16:39.087 10613 10639 E AndroidRuntime: 	at com.badlogic.gdx.pay.PurchaseSystem.purchase(PurchaseSystem.java:194)
08-02 18:16:39.087 10613 10639 E AndroidRuntime: 	at screens.GameScreen.TipStore$3.run(TipStore.java:124)
08-02 18:16:39.087 10613 10639 E AndroidRuntime: 	at screens.GameScreen.TipStore$BuyButton$1.clicked(TipStore.java:70)
08-02 18:16:39.087 10613 10639 E AndroidRuntime: 	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:89)
08-02 18:16:39.087 10613 10639 E AndroidRuntime: 	at screens.GameScreen.TipStore$BuyButton$1.touchUp(TipStore.java:62)
08-02 18:16:39.087 10613 10639 E AndroidRuntime: 	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:57)
08-02 18:16:39.087 10613 10639 E AndroidRuntime: 	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:348)
08-02 18:16:39.087 10613 10639 E AndroidRuntime: 	at com.badlogic.gdx.backends.android.AndroidInput.processEvents(AndroidInput.java:360)
08-02 18:16:39.087 10613 10639 E AndroidRuntime: 	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:420)
08-02 18:16:39.087 10613 10639 E AndroidRuntime: 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1551)
08-02 18:16:39.087 10613 10639 E AndroidRuntime: 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1268)
08-02 18:16:39.087 10613 10639 I AndroidRuntime: To Report FATAL to activityManagerService

**Comment by MrStahlfelge** [comment]
I think this can be closed. We have #128 on how to use on Amazon devices and #159 for discussing if PurchaseSystem should be used anymore.

**Comment by keesvandieren** [comment]
Thanks for your input!
