### ISSUE TITLE
PurchaseVerifieriOSApple problems

### ISSUE THREAD

**Issue by piotr-j** [libgdx/gdx-pay#166]
It seems that it is a bit out of date, at least for sandbox purchases. 

`String receipt = transaction.getTransactionData();` should most likely use `getTransactionDataSignature` instead and not b64 it as it already is. 
Additionally, the result seems to be formatted differently, status is on the second line, with just single { on the first. The parsing fails due to that.

**Comment by noblemaster** [comment]
You are correct, the correct method is `getTransactionDataSignature()`!

**Comment by MrStahlfelge** [comment]
Thanks for your PR. I think this issue can be closed now?
