### ISSUE TITLE
Android IAP type ENTITLEMENT with Gdx-pay requestPurchaseRestore().

### ISSUE THREAD

**Issue by hoangtunho2611** [libgdx/gdx-pay#176]
Hi,

I have a problem with the IAP with Gdx-pay on Android. How to:
1. Remove the IAP item type ENTITLEMENT (Remove ads) purchased with the my account test.
2. Set the IAP item type ENTITLEMENT (Remove ads) to the purchased value when the user purchases a CONSUMABLE item. In this case I save a value on data to know that item type ENTITLEMENT (purchased ads) purchased. But if that account is logged on to another device then the item type ENTITLEMENT (Remove ads) has not been purchased.

To returns the correct result when call: getPlatformResolver (). requestPurchaseRestore ();

Thanks,

**Comment by keesvandieren** [comment]
On Android entitlements (one-time purchases) are shared automatically between devices, we are using that  using `gdx-pay-android-googleplay` implementation.

Which implementation are you using? If this doesn't work, there is either something wrong with gdx-pay client code or the devices have different accounts.

Also, on first launch of second device, internet connection should be available. 

On launch, you should call `com.badlogic.gdx.pay.PurchaseManager.purchaseRestore()`. 

Asynchronously `com.badlogic.gdx.pay.PurchaseObserver#handleRestore()` is called to communicate the result, which contains existing ENTITLEMENT transaction for that user.

If you have a reproducible example that demonstrates the problem, share it as git repository and we will take a look at it.

**Comment by hoangtunho2611** [comment]
Hi @keesvandieren 

Thank you for answering me.
Perhaps you have not understood my problem. I use Gdx-pay for android and have published my game on google play. Transactions, payments everything works well. But as I said above.
1. With my test account. I purchased ENTITLEMENT successfully (Test Order). And now, when I play my game (install from google play). Call purchaseRestore () will return containing ENTITLEMENT transaction. Here, how to delete ENTITLEMENT transaction with my test account?
2. The user will purchase a CONSUMABLE successfully. And I included ENTITLEMENT (Remove Ads), so how to hardcode ENTITLEMENT transaction? To call purchaseRestore () will return the ENTITLEMENT transaction.
I hope you understand me!

**Comment by keesvandieren** [comment]
Question (1) is clear. If you are using `gdx-pay-android-googleplay` module, you can call `cancelTestPurchases` on PaymentManager. It is not implemented for other implementations. We have the following Kotlin code:

    fun cancelTestPurchases() {
        val manager = PurchaseSystem.getManager()
        if (manager is PurchaseManagerTestSupport) {
            manager.cancelTestPurchases()
        } else {
            throw IllegalStateException("cancelTestPurchases() not supported by PurchaseManager.")
        }
    }

Question 2: is your question how to  persist CONSUMABLE purchases?
