### ISSUE TITLE
Crash in PurchaseManageriOSApple.transaction - XC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000

### ISSUE THREAD

**Issue by Arsalana** [libgdx/gdx-pay#179]
Hello all,

Right now I am seeing crash in my game at the following callstack. Is this something already known?

XC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000
[J]com.badlogic.gdx.pay.ios.apple.PurchaseManageriOSApple.transaction(Lorg/robovm/apple/storekit/SKPaymentTransaction;)Lcom/badlogic/gdx/pay/Transaction;

Crashed: com.apple.main-thread
0  NumberGo                       0x102c14f84 [J]com.badlogic.gdx.pay.ios.apple.PurchaseManageriOSApple.transaction(Lorg/robovm/apple/storekit/SKPaymentTransaction;)Lcom/badlogic/gdx/pay/Transaction; (PurchaseManageriOSApple.java:242)
1  NumberGo                       0x102c14f7c [J]com.badlogic.gdx.pay.ios.apple.PurchaseManageriOSApple.transaction(Lorg/robovm/apple/storekit/SKPaymentTransaction;)Lcom/badlogic/gdx/pay/Transaction; (PurchaseManageriOSApple.java:242)
2  NumberGo                       0x102c16bb8 [J]com.badlogic.gdx.pay.ios.apple.PurchaseManageriOSApple$AppleTransactionObserver.updatedTransactions(Lorg/robovm/apple/storekit/SKPaymentQueue;Lorg/robovm/apple/foundation/NSArray;)V (PurchaseManageriOSApple$AppleTransactionObserver.java:360)
3  NumberGo                       0x102c183b4 [J]com.badlogic.gdx.pay.ios.apple.PurchaseManageriOSApple$IosFetchProductsAndInstallDelegate.didReceiveResponse(Lorg/robovm/apple/storekit/SKProductsRequest;Lorg/robovm/apple/storekit/SKProductsResponse;)V (PurchaseManageriOSApple$IosFetchProductsAndInstallDelegate.java:337)
4  NumberGo                       0x102c18660 [J]com.badlogic.gdx.pay.ios.apple.PurchaseManageriOSApple$IosFetchProductsAndInstallDelegate.$cb$productsRequest$didReceiveResponse$(Lcom/badlogic/gdx/pay/ios/apple/PurchaseManageriOSApple$IosFetchProductsAndInstallDelegate;Lorg/robovm/objc/Selector;Lorg/robovm/apple/storekit/SKProductsRequest;Lorg/robovm/apple/storekit/SKProductsResponse;)V + 4311893600
5  NumberGo                       0x102c17fa0 [j]com.badlogic.gdx.pay.ios.apple.PurchaseManageriOSApple$IosFetchProductsAndInstallDelegate.$cb$productsRequest$didReceiveResponse$(Lcom/badlogic/gdx/pay/ios/apple/PurchaseManageriOSApple$IosFetchProductsAndInstallDelegate;Lorg/robovm/objc/Selector;Lorg/robovm/apple/storekit/SKProductsRequest;Lorg/robovm/apple/storekit/SKProductsResponse;)V[callback] + 4311891872
6  StoreKit                       0x198fc40c0 __34-[SKProductsRequest _handleReply:]_block_invoke + 512
7  libdispatch.dylib              0x1849b8b24 _dispatch_call_block_and_release + 24
8  libdispatch.dylib              0x1849b8ae4 _dispatch_client_callout + 16
9  libdispatch.dylib              0x1849c56e0 _dispatch_main_queue_callback_4CF$VARIANT$mp + 1012
10 CoreFoundation                 0x18506f070 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
11 CoreFoundation                 0x18506cbc8 __CFRunLoopRun + 2272
12 CoreFoundation                 0x184f8cda8 CFRunLoopRunSpecific + 552
13 GraphicsServices               0x186f6f020 GSEventRunModal + 100
14 UIKit                          0x18ef6d78c UIApplicationMain + 236
15 NumberGo                       0x10335c680 [J]org.robovm.apple.uikit.UIApplication.main(ILorg/robovm/rt/bro/ptr/BytePtr$BytePtrPtr;Ljava/lang/String;Ljava/lang/String;)I + 4319512192
16 NumberGo                       0x10335ba38 [J]org.robovm.apple.uikit.UIApplication.main([Ljava/lang/String;Ljava/lang/Class;Ljava/lang/Class;)V (UIApplication.java:428)
17 NumberGo                       0x10335ab18 [j]org.robovm.apple.uikit.UIApplication.main([Ljava/lang/String;Ljava/lang/Class;Ljava/lang/Class;)V[clinit] + 4319505176
18 NumberGo                       0x102cc387c [J]com.rsgamesllc.numbergo.IOSLauncher.main([Ljava/lang/String;)V (IOSLauncher.java:102)
19 NumberGo                       0x1035d1ac0 _call0 + 4322089664
20 NumberGo                       0x1035c79cc callVoidMethod + 4322048460
21 NumberGo                       0x1035ca2f0 rvmCallVoidClassMethodA + 4322058992
22 NumberGo                       0x1035ca38c rvmCallVoidClassMethod + 4322059148
23 NumberGo                       0x1035c228c rvmRun + 4322026124
24 NumberGo                       0x1035b78c8 main + 4321982664
25 libdyld.dylib                  0x184a1dfc0 start + 4

Thanks,

Arsalan

**Comment by keesvandieren** [comment]
I think you are not using last version? I know we had this issue in old version.

**Comment by MrStahlfelge** [comment]
Closed because not answering.
