### ISSUE TITLE
You have forgot to add the BillingClient.endConnection() to the PurchaseManagerGoogleBilling.dispose() method

### ISSUE THREAD

**Issue by ProZhar** [libgdx/gdx-pay#180]
https://github.com/libgdx/gdx-pay/blob/1dade184a96dae53a758988482f4d7397b27249a/gdx-pay-android-googlebilling/src/com/badlogic/gdx/pay/android/googlebilling/PurchaseManagerGoogleBilling.java#L170-L178

In javadocs of BillingClient.java it says:

> When you are done with this object, don't forget to call endConnection() to ensure proper cleanup. This object holds a binding to the in-app billing service and the manager to handle broadcast events, which will leak unless you dispose it correctly. If you created the object inside the onCreate(Bundle) method, then the recommended place to dispose is the the onDestroy() method.

[BillingClient.java](https://developer.android.com/reference/com/android/billingclient/api/BillingClient)

The TrivialDrive v2 sample app shows this has endConnection() too:
```java
public void destroy() {
        Log.d(TAG, "Destroying the manager.");

        if (mBillingClient != null && mBillingClient.isReady()) {
            mBillingClient.endConnection();
            mBillingClient = null;
        }
    }
```
[TrivialDrive v2 sample app BillingManager.java](https://github.com/googlesamples/android-play-billing/blob/180077a516d79e465435a4917d06b054999f82c0/TrivialDrive_v2/shared-module/src/main/java/com/example/billingmodule/billing/BillingManager.java#L170-L177)

I use PurchaseManager.dispose() on the Game.dispose()

In this case all good:
start app->
start purchase->
cancel purchase->
**home button**->
start app->
start purchase->
cancel purchase 

But I see crashes in this case:
start app->
start purchase->
cancel purchase->
**back button** (this causes Gdx.app.exit() in my case and PurchaseManager.dispose()) ->
start app->
start purchase->
cancel purchase->
-> CRASH REPORT 

```java
 com.prozhar.ua.spelling E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.prozhar.ua.spelling, PID: 24311
    java.lang.NullPointerException: Attempt to invoke interface method 'void com.badlogic.gdx.pay.PurchaseObserver.handlePurchaseCanceled()' on a null object reference
        at com.badlogic.gdx.pay.android.googlebilling.PurchaseManagerGoogleBilling.onPurchasesUpdated(PurchaseManagerGoogleBilling.java:211)
        at com.android.billingclient.api.BillingClientImpl$1.onReceive(BillingClientImpl.java:136)
        at com.android.billingclient.api.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:303)
        at com.android.billingclient.api.LocalBroadcastManager.access$000(LocalBroadcastManager.java:44)
        at com.android.billingclient.api.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:114)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

Sorry for my english. Fix it faster plaese
I use your perfect library in production. :)

**Comment by ProZhar** [comment]
@keesvandieren can you fix it, please
I have many crashing in production, if people close the app, and then start again it creates multiple connections, early connections don't have observer because it is disposed

**Comment by keesvandieren** [comment]
@MrStahlfelge there seems to be an issue in GoogleBilling implementation. Can you have a look at it?

@ProZhar if you understand the code, you can submit a PR.

**Comment by ProZhar** [comment]
> 2\. Crash after calling dispose => the stack trace shows that calling the observer's purchaseCancelled() method fails. This is because the observer is set to null in dispose while a request is performed. I assume purchaseRestore() is called on game start and users immediately closing the game see the crash. This can be fixed by adding null checks to all observer calls from callbacks, but I recommend not to call purchaseRestore automatically.

I think you are right. In my debuging process (see below) I see google keeps all connection where not called endConnection().

**Comment by ProZhar** [comment]
@MrStahlfelge 
> 2\. Crash after calling dispose => the stack trace shows that calling the observer's purchaseCancelled() method fails. This is because the observer is set to null in dispose while a request is performed. I assume purchaseRestore() is called on game start and users immediately closing the game see the crash. This can be fixed by adding null checks to all observer calls from callbacks, but I recommend not to call purchaseRestore automatically.

In my case I don't call purchaseRestore() on Game.create(). The purchaseRestore() is called only the player press the RestoreButton. I check it, the observer.handleInstall() is forever called before purchaseRestore().

**Comment by ProZhar** [comment]
@MrStahlfelge 
[This is my app](https://play.google.com/store/apps/details?id=com.prozhar.math&hl=en)
You can try this test:
1. Launch app
2. Click Shop (bottom-left corner)
3. Click some purchase
4. Cancel the purchase via by pressing anywhere outside of the purchase window or android back button
5. Close app via android home button
6. Launch apps menu and click Clear All (purchase.dispose() not called because Game.dispose() not called)
7. Do 1-4 again and you will not see crach
6. Press android back button and confirm exit from app (there is called purchase.dispose())
8. Do 1-4 again and you will see the crash

**Comment by MrStahlfelge** [comment]
Please build the new version locally and test if this fixes your issues.

**Comment by ProZhar** [comment]
@keesvandieren will you release the new version or use a local build?

**Comment by keesvandieren** [comment]
@ProZhar the error is because gdx-pay was not yet updated to latest android-build-tools version. Had a quarter of time tonight, but still some errors to go: https://github.com/libgdx/gdx-pay/tree/android-build-tools-3-upgrade

Will continue when I have time, may take a while. If you have time to take it, would be appreciated :-)

**Comment by MrStahlfelge** [comment]
This issue can be closed.
