### ISSUE TITLE
Restored transactions array is empty.

### ISSUE THREAD

**Issue by IskanderNazarov** [libgdx/gdx-pay#186]
Hi. I'm trying to restore the already bought transactions, I do the next steps

```
purchaseManager = ScreenManager.getInstance().getGame().purchaseManager;
PurchaseManagerConfig pmc = new PurchaseManagerConfig();
for (String id : IAP_Manager.inst.IDS()) {
   pmc.addOffer(new Offer().setType(OfferType.CONSUMABLE).setIdentifier(id));
}

 purchaseManager.install(this, pmc, true);
```

When purchase manager is installed I do this

```
@Override
public void handleInstall() {
     purchaseManager.purchaseRestore();
}
```

After this the next code works
```
@Override
public void handleRestore(Transaction[] transactions) {
     System.out.println("IAP__ restored count = " + transactions.length);
}
```

But in console it prints  `IAP__ restored count = 0`, though I has made several purchases
Under iOS it works fine, but for android the restored count is always zero.

P.S.
For each market I use its own products ids.

**Comment by MrStahlfelge** [comment]
Please state which Android IAP implementation you are using: googleplay, googlebilling or amazon?

**Comment by IskanderNazarov** [comment]
I'm using googleplay, I assume.
This is what I have in my gradle file 
```
implementation "com.badlogicgames.gdxpay:gdx-pay-android:$gdxPayVersion"
        implementation "com.badlogicgames.gdxpay:gdx-pay-android-googleplay:${gdxPayVersion}@aar"
```
where `gdxPayVersion = '0.11.2'`

**Comment by MrStahlfelge** [comment]
Please try googlebilling implementation with v11.4-SNAPSHOT if it works better for you.

In any case, it is recommended not to call purchaseRestore on every install ([see here](https://github.com/libgdx/gdx-pay#restore-purchases))

**Comment by IskanderNazarov** [comment]
I call purchasesRestore only for Android, this is ok, isn't it?

**Comment by IskanderNazarov** [comment]
Thanks very much, everything works perfectly with `googlebilling`

**Comment by MrStahlfelge** [comment]
Great to hear! 👍
