### ISSUE TITLE
These in-app purchases can’t be promoted on the App Store because your latest approved binary doesn’t include the SKPaymentTransactionObserver method.

### ISSUE THREAD

**Issue by gagbaghdas** [libgdx/gdx-pay#192]
Hi guys.

I see, that this issue should be resolved in gdx-pay-0.11.3-SNAPSHOT. 

But I receive this warning message from Apple now.

I'm using 0.12.1-SNAPSHOT version.

Maybe I missed adding some part of implementation? But it seems no 😃 .

So, please, could you look into it?

**Comment by MrStahlfelge** [comment]
Why don't you use 0.12.0?

**Comment by gagbaghdas** [comment]
Hi @MrStahlfelge. Thanks for the answer. I used 0.12.0, then, after seeing this issue, trying to use 0.12.1-SNAPSHOT, but nothing changed. So there is no difference between 0.12.0 and 0.12.1-SNAPSHOT regarding this issue.

**Comment by MrStahlfelge** [comment]
Are you using RoboVM or MOE?

**Comment by gagbaghdas** [comment]
I'm using RoboVM(MobiVM's fork).

**Comment by gagbaghdas** [comment]
P.S., I tested with

itms-services://?action=purchaseIntent&bundleId=[my game bundle id]&productIdentifier=[sku]

and it didn't work ) so , I think there is a problem and it isn't on Apple's side)

**Comment by keesvandieren** [comment]
Hi @MrStahlfelge , @gagbaghdas, 

For #175 I implemented a required method for promoting IAP in App Store. @Glyfad never confirmed whether it worked.  So it has not been tested so far.

I have never read through the developer guide of Apple, of how to implement it, I just followed instructions provided by @Glyfad. https://github.com/libgdx/gdx-pay/commit/92ad0b70624e7e87d06f2f0e102d673a7e26666b

So it is perfectly possible that it is not yet working well. We are willing to accept PRs to do additional required code changes.

**Comment by MrStahlfelge** [comment]
@gagbaghdas Apple's error message says the _last approved binary_ is concerned. I doubt that you were able to test the new versions that fast, in my experiences it takes at least a day until a new version is approved.

Please also state how we can reconstruct a problem. A link to App Store Connect does not work, please tell us how to go to this error message.

**Comment by gagbaghdas** [comment]
@MrStahlfelge I'm seeing this message for about a week already. So, there is no problem with the version approval. 

I implemented PurchaseManageriOSApple in my game. In-app purchases work well, so, there is no problem with the implementation in general. I didn't do anything special for the app store promotions. So, you can just implement the  PurchaseManageriOSApple, as you do it for the purchases and try to upload to the app store connect. 

Here is the screenshot, where I'm seeing the message.

![Screen Shot 2019-04-11 at 4 12 57 PM](https://user-images.githubusercontent.com/16702414/55956326-c30ece80-5c74-11e9-907d-4020c1d4aabf.png)

P.S., "SKPaymentTransactionObserver method" in the message has a link, and when you click on it, you go to the 
https://developer.apple.com/documentation/storekit/skpaymenttransactionobserver/2877502-paymentqueue

**Comment by MrStahlfelge** [comment]
I'll check later if I have this warning in my app store connect with an approved and released 0.12.1-SNAPSHOT.

**Comment by gagbaghdas** [comment]
Thanks @MrStahlfelge ) I'll continue trying to understand what's going on.

**Comment by gagbaghdas** [comment]
P.S. @MrStahlfelge, you can test it with the following call. 

Click on your ios device on the following link.

itms-services://?action=purchaseIntent&bundleId=[my game bundle id]&productIdentifier=[sku]

In my case, when I click on this link , it opens my game, but nothing happened regarding buying the product with the sku. 

So, I think , you can test it without uploading to the app store connect.

**Comment by gagbaghdas** [comment]
@MrStahlfelge  from the logs, I found the following message. 

[SKPaymentQueue]: Tried to send purchase intent: [product_sku] to delegate, delegate does not respond to method paymentQueue:shouldAddStorePayment:forProduct

[product_sku] -  is the SKU, of the in-app purchase, that in the 

itms-services://?action=purchaseIntent&bundleId=[my game bundle id]&productIdentifier=[sku]

Any ideas?

**Comment by gagbaghdas** [comment]
@MrStahlfelge I'm closing this issue, for now, As I was able to successfully test flow on a simple app with hardcoded skus. Thanks for your help.

**Comment by keesvandieren** [comment]
Where you able to test with gdxpay or just plain robovm?

**Comment by gagbaghdas** [comment]
With gdx-pay)

**Comment by gagbaghdas** [comment]
@keesvandieren @MrStahlfelge  I have the following problem.

I install the initialize my PurchaseManager in the top of the didFinishLaunching method, but, actually, it isn't inited in most of the cases (I mean, sometimes it inited in time, and the flow works well, sometimes, no), when Apple wants to call it for the iaps, when you click on the link. 

It works well When it already inited and, for example, my game in the background, and I click on the link. 

I tried to init my PurchaseManager in createApplication method, but the result is the same.

So, maybe you have any suggestions?

**Comment by gagbaghdas** [comment]
IMPORTANT UPDATE. 

It works well when I add the following method in the didFinishLaunching method.

```
SKPaymentTransactionObserverAdapter workaround = new SKPaymentTransactionObserverAdapter() {
            @Override
            public boolean shouldAddStorePayment(SKPaymentQueue queue, SKPayment payment, SKProduct product) {
                return true;
            }
        };
        SKPaymentQueue.getDefaultQueue().addTransactionObserver(workaround);
        SKPaymentQueue.getDefaultQueue().addStrongRef(workaround);
```

Thanks to Demyan Kimitsa for help :)

**Comment by MrStahlfelge** [comment]
Yes. The problem cause is that PurchaseManageriOSApple installs the transaction observer after fetching the products, which is too late. I don't know if this is in purpose. The transaction observer itself does not access the products, but I just did a quick check and I am not sure if I missed side effects.

**Comment by gagbaghdas** [comment]
@MrStahlfelge Thanks a lot. Please, let me know if I can help with anything. ))

**Comment by MrStahlfelge** [comment]
Found it. The observer needs product access in updatedTransactions.

@gagbaghdas With your work-around, what happens with the purchased items when your game starts cold: Is the purchase reliably reported to your PurchaseObserver#handlePurchase method?

**Comment by gagbaghdas** [comment]
Yes))

**Comment by MrStahlfelge** [comment]
Good to hear, then we can integrate the same workaround into PurchaseManageriOSApple. Are you able to test a snapshot this weekend?

**Comment by gagbaghdas** [comment]
Sure . I'll wait for your confirmation. Thank you))

**Comment by MrStahlfelge** [comment]
Published a new 0.12.1-SNAPSHOT with the workaround. Please let me know if this works for you. (Please check if you really got the latest snapshot, refreshing snapshots is sometimes fiddly)

**Comment by MrStahlfelge** [comment]
Ah, please wait... I saw a copy/paste mistake :(

**Comment by MrStahlfelge** [comment]
Okay, fixed. :)

**Comment by gagbaghdas** [comment]
@MrStahlfelge  hi, thank you. 
It works :)

**Comment by MrStahlfelge** [comment]
That's great to hear! I will publish release 0.12.1 within the next two weeks. If you experience any problems in the meantime, please let us know.

**Comment by gagbaghdas** [comment]
Sure @MrStahlfelge , Thanks again. 

P.S., I have 2 questions. 

1. Is there any way to install the PurchaseManager and change config later? Because I get sku's from a backend and don't have them in didFinishLaunching (
2. Is there any way to hold the call of handlePurchase or something like this? The problem is that for this feature, Apple call purchase as soon as game starts, so there is still loading screen(

Thanks.

**Comment by gagbaghdas** [comment]
@MrStahlfelge ,  Apple [says](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/StoreKitGuide/PromotingIn-AppPurchases/PromotingIn-AppPurchases.html) , that 

If your app needs to defer transaction, you return false. For example, you may need to defer a transaction if the user is in the middle of onboarding, and continue it after onboarding is completed. 

To defer a transaction:

1.  Save the payment to use when the app is ready. The payment already contains information about the product. Do not create a new SKPayment with the same product.
2.  Return false from shouldAddStorePayment method
3.  After the user is finished with onboarding or other actions that required a deferral, send the saved payment to the payment queue, the same way you would with a normal in-app purchase.

I'm not sure what they mean by saying "Save the payment to use when the app is ready. ". Could you please help me. How can I do it with gdxpay?

Thanks.

**Comment by MrStahlfelge** [comment]
1. You can dispose and reinstall the PurchaseObserver at any time.
2. you said you get the callback to your purchaseobserver reiliably. so you can process the payment however you want

**Comment by gagbaghdas** [comment]
@MrStahlfelge what do you think about the following idea?

In PurchaseManageriOSApple. 
1. add the following variable.

```
private SKPayment promotionalPayment;
```

2. Change the following code to 

```
    private class PromotionTransactionObserver extends SKPaymentTransactionObserverAdapter {
        @Override
        public boolean shouldAddStorePayment(SKPaymentQueue queue, SKPayment payment, SKProduct product) {
if(!addStorePayments){
promotionalPayment = payment;
}
            return addStorePayments;
        }
    }
```

3. add the following method

```
public void purchasePromotionalProduct(){
     if(promotionalPayment != null){
          SKPaymentQueue.getDefaultQueue().addPayment(promotionalPayment);
          promotionalPayment = null;
      }
}
```

What do you think?

P.S. I see in the PurchaseManageriOSApple you wrote

```
if (this.appleObserver == null) {
                this.startupTransactionObserver = new PurchaseManageriOSApple.PromotionTransactionObserver();
....
```

Why do you check for null the appleObserver during startupTransactionObserver init?

Sorry, if I misunderstand anything )

P.S. 2.  I tried to implement 2 observers, and it worked, when the game closed. But when the game opened and in the background and I try to test the flow, the same transaction purchases 2 times ) And after the 2nd purchase, Apple says, that "This In-App purchase has already been bought. It will be restored for free". ( Any ideas why the same transaction is being completed 2 times?

Thanks.

**Comment by MrStahlfelge** [comment]
I don't think a change to the core interface is needed, as you said the purchase is reported to your observer anyway. You can store this purchase in an own variable, do your work to start up your game and then process the purchase in your gui.

I don't unterstand the second issue with two observers.

**Comment by gagbaghdas** [comment]
@MrStahlfelge I tried to create MyPurchaseManageriOSApple and add the code mentioned above and it works as expected.

The problem with "You can store this purchase in an own variable, do your work to start up your game and then process the purchase in your gui." is that if you return true from shouldAddStorePayment, the payment is being added to the defaultQueue automatically and I'm seeing the Apple's prompt about purchase during loading screen. But if you return false, and from shouldAddStorePayment and serve the Payment object for later, it works as expected. e.g. you have control when to add to the defaultQueue the promotional Payment object and when show Apple's prompt about the purchase to the User. 

About 2nd issue, I'm trying to reproduce now why the same transaction is being completed twice.

**Comment by gagbaghdas** [comment]
@MrStahlfelge FOUND THE 2ND ISSUE. 

1. I have added the following variable to the MyPurchaseManageriOSApple.
```
    private boolean startupTransactionObserverInstalled;

```

2. And  changed the following code to 

```
 if (!startupTransactionObserverInstalled) {
                startupTransactionObserverInstalled = true;
                // Installing intermediate observer to handle App Store promotions
                ....
            }
```

And the bug with double transactions was fixed. It seems the problem was in the following 

```
 if (appleObserver == null) {
                // Installing intermediate observer to handle App Store promotions
.....
```

As the new (2nd) PromotionTransactionObserver was installed during appleObserver install. 

Thanks for your help.

Are you going to add these 2 fixes (the above one and this one) to the 0.12.1-SNAPSHOT or no?
Because with these 2 fixes the feature is worked perfectly for all cases) 
Please, let me know, if you are going to add these fixes to the SNAPSHOT, I'll remove MyPurchaseManageriOSApple and will use PurchaseManageriOSApple from the build. 

Thank you for your help.

**Comment by MrStahlfelge** [comment]
This problem indicates you really call `install()` more than once. 

I would prefer to use this condition:

     if (appleObserver == null && startupTransactionObserver == null)

This should be the same, but please test this.

**Comment by gagbaghdas** [comment]
@MrStahlfelge Thanks. 
Yes, I call install() twice, but before the second install() I call the dispose().

Ok, Will test now and let you know how it works.

Thanks.

**Comment by gagbaghdas** [comment]
Yes @MrStahlfelge you are right. The result is same :) 

So, are you going to add these 2 changes to the SNAPSHOT?

Thanks.

**Comment by MrStahlfelge** [comment]
Which is the second change?

**Comment by gagbaghdas** [comment]
Regarding promotionalPayment object. 
Please, see above. 

Thanks.

**Comment by gagbaghdas** [comment]
@MrStahlfelge , Please, check [here](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/StoreKitGuide/PromotingIn-AppPurchases/PromotingIn-AppPurchases.html)  "Deferring or Canceling a Transaction" section . 

I implemented the same, as I mentioned [here](https://github.com/libgdx/gdx-pay/issues/192#issuecomment-482855453). 

Please, let me know , if you are going to include these changes too. 

Thank you.

**Comment by MrStahlfelge** [comment]
Hi, I commited a fix for issue 2.

I also made it possible to override the behaviour on how the promotional purchases are processed. This way, if you use the PurchaseManager without any changes, the purchase is processed as soon as possible. But if you need other behaviour as you do, you can override this in an own subclass by overriding the method shouldProcessPromotionalStorePayment. You can do your own logic you suggested in this slim subclass without needing to copy the whole iOS purchase manager. I think that's the best solution and this way the code for the different use cases is seperated.

**Comment by gagbaghdas** [comment]
@MrStahlfelge Thanks. I'm closing the issue.

Just in case, if anyone needed.

```
import com.badlogic.gdx.pay.ios.apple.PurchaseManageriOSApple;

import org.robovm.apple.storekit.SKPayment;
import org.robovm.apple.storekit.SKPaymentQueue;
import org.robovm.apple.storekit.SKProduct;

public class MyPurchaseManageriOSApple extends PurchaseManageriOSApple {

    private SKPayment promotionalPayment;
    private boolean shouldProcessPromotionalStorePayment = true;

    @Override
    protected boolean shouldProcessPromotionalStorePayment(SKPaymentQueue queue, SKPayment payment, SKProduct product) {
        if (!shouldProcessPromotionalStorePayment) {
            promotionalPayment = payment;
        }
        return shouldProcessPromotionalStorePayment;
    }

    // Call this method to process saved promotional product later
    public void purchasePromotionalProduct(){
        if(promotionalPayment != null){
            SKPaymentQueue.getDefaultQueue().addPayment(promotionalPayment);
            promotionalPayment = null;
        }
    }
    
    public void enablePromotionalStorePayment() {
        shouldProcessPromotionalStorePayment = true;
    }

    public void disablePromotionalStorePayment() {
        shouldProcessPromotionalStorePayment = false;
    }
}

```

Thanks to all for help.

**Comment by kopolop** [comment]
Hello, what is the final resolution for this? 

We're using gdx Pay 0.12.1 and facing the same issue

We modify the IOS Purcharse Manager per your suggestion in this comment https://github.com/libgdx/gdx-pay/issues/192#issuecomment-483005957

However we're not sure if this is good enough or we need to modify didFinishLaunching as well per this comment https://github.com/libgdx/gdx-pay/issues/192#issuecomment-482581933
