### ISSUE TITLE
Module: core "implementation" instead of "compile"

### ISSUE THREAD

**Issue by apelt** [libgdx/gdx-pay#202]
#### Issue details, reproduction steps/code
If I change the import of  gdx-pay dependency in the core module of the main build.gradle from:
**compile**"com.badlogicgames.gdxpay:gdx-pay-client:$gdxPayVersion"
to:
**implementation** "com.badlogicgames.gdxpay:gdx-pay-client:$gdxPayVersion"

#### Version of gdx-pay and/or relevant dependencies
gdxPayVersion = '1.0.0'
gdxVersion = '1.9.9'

#### Stacktrace
error: com.badlogic.gdx.pay.PurchaseManager: class file for com.badlogic.gdx.pay.PurchaseManager not found
C:\Users\XXXX\LibGDXProjects\XXXX\desktop\src\com\example\game\desktop\DesktopLauncher.java:13: error: cannot access PurchaseManager
public class DesktopLauncher {
       ^
  class file for com.badlogic.gdx.pay.PurchaseManager not found
1 error
1 warning

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':desktop:compileJava'.
> Compilation failed; see the compiler error output for details.

#### Please select the affected platforms and payment service implementation
-gdxpay when trying to launch the project on Desktop from Android Studio on Windows 10

You can reproduce this error with the example app at:
https://github.com/libgdx/gdx-pay-example
as well. When there is a any class from com.badlogic.gdx.pay imported in the DesktopLauncher the error is: 
  symbol:   class PurchaseManager
  location: package com.badlogic.gdx.pay
C:\Users\Petr777\XXXX\gdx-pay-example-master\desktop\src\com\badlogic\gdx\pay\app\DesktopLauncher.java:8: error: cannot find symbol
import com.badlogic.gdx.pay.PurchaseManagerConfig;

**Note:**
I am not sure if this really is a bug, but I guess you know that when using "compile", Android Studio shows warning like this:
_Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018._

**Comment by MrStahlfelge** [comment]
You can safely ignore this warning. We'll switch to implementation/api when the main gdx project switches.
