### ISSUE TITLE
Using an old version of the Google Play Developer API. From December 1 2019

### ISSUE THREAD

**Issue by Vlad-Imir1901** [libgdx/gdx-pay#205]
Please ensure you have given all the following requested information in your report.

#### Issue details, reproduction steps/code
Everything is working perfectly so far. But I got a message from Google Play Developer Support as follow:
"We've detected that your app is using an old version of the Google Play Developer API. From December 1 2019, versions 1 and 2 of this API will no longer be available. Update to version 3 before this date. Note that this is not related to the AIDL/Billing Library deprecation."
So, should I do something with this?

#### Version of gdx-pay and/or relevant dependencies
0.11.2

#### Stacktrace
```java
//Please provide the stacktrace if applicable 
```

#### Please select the affected platforms and payment service implementation
- [ ] Amazon
- [ ] googlebilling
- [x ] googlepay
- [ ] apple iosmoe
- [ ] apple robovm

**Comment by MrStahlfelge** [comment]
Do you use server side verification?

**Comment by Vlad-Imir1901** [comment]
To: MrStahlfelge
I guess no.

I use as a base code this sample Berobasket/gdx-pay-issue:
https://github.com/Berobasket/gdx-pay-issue/tree/66d37d5bcb37fb76da429bd9ef0e7e8c572cba1d/core/src/pl/com/berobasket/gdxpayissue

Additional info: type of purchase Non-Consumable
gdxVersion         = '1.9.6'
gdx-pay              = '0.11.2'

**Comment by MrStahlfelge** [comment]
Then I think you have nothing to do, but you should switch to googlebilling before 2021.

**Comment by Vlad-Imir1901** [comment]
Thanks MrStahlfelge for your answer.

I would kindly appreciate if you make clear some issues as follow:

1. They refer to 1st of December 2019 (not 2021), should I ignore that message?
2. If 2021 is a red line then will I have to recreate part of my code (switch to googlebilling )?

**Comment by MrStahlfelge** [comment]
1. They refer to the Google Play Developer API. I don't know what you use it for, so I don't know if you can ignore the message.

2. Yes, it is April 2021 IIRC.

**Comment by Vlad-Imir1901** [comment]
1. I use libgdx + gdx-pay. Nothing more.

**Comment by MrStahlfelge** [comment]
You see, it has nothing to do with gdx-pay.
