### ISSUE TITLE
Google Play Promo Codes not working

### ISSUE THREAD

**Issue by asdf-qwert** [libgdx/gdx-pay#207]
Hello, the use of promo codes does not work.
I enter the code in Google Play, then enter the app (does not matter if it is running or not) and nothing happens... I would expect that `PurchaseObserver#handlePurchase` gets called.
Is it a bug or it is just not implemented?

Also the product I was given by promo code can no longer be purchased as the `ItemAlreadyOwnedException` is thrown.

**Comment by MrStahlfelge** [comment]
Neither a bug, nor not implemented. If you want to support purchasements that are done from outside the app you need to restore the purchases: https://github.com/libgdx/gdx-pay#restore-purchases
