### ISSUE TITLE
gdx-pay-android-googlebilling does not support subscriptions

### ISSUE THREAD

**Issue by keesvandieren** [libgdx/gdx-pay#210]
gdx-pay-android-googlebilling does not yet support subscriptions.

Only IN_APP is supported currently, as it is always set as SkuType: https://github.com/libgdx/gdx-pay/blob/master/gdx-pay-android-googlebilling/src/com/badlogic/gdx/pay/android/googlebilling/PurchaseManagerGoogleBilling.java#L123

#### Please select the affected platforms and payment service implementation
- [ ] Amazon
- [X] googlebilling
- [ ] googlepay
- [ ] apple iosmoe
- [ ] apple robovm

The problem is that you can only set one SkuType per query, and that it is mandatory. 

I am going to implement an improvement: add support for subscriptions. One GoogleBilling client then supports either subscriptions or in app, but not both at the same time.

While it is possible to implement both at the same time, it takes more effort to do so, and I don't need that functionality yet, so it is hard to verify it actually works correctly as I don't have an app with both used together.

@MrStahlfelge  ok if I implement it that way, to mutually exclusive IN_APP and Subscription SkuType?

**Comment by MrStahlfelge** [comment]
Soure, every enhancement is better than the current state. 

But I think it is possible to use only a single client: `purchase()`-method is okay as it is in your version. `purchaseRestore()` could make two calls. The only complicated thing is the sku details setup.

**Comment by keesvandieren** [comment]
Solved the issue as with pr #211
