### ISSUE TITLE
Expose Subscription  Subscription Introductory Offer period

### ISSUE THREAD

**Issue by keesvandieren** [libgdx/gdx-pay#220]
Subscriptions in Google Play and App Store support a trial period, in which users can try-out the app for free or for a reduced price. 

This information is not yet exposed to gdxpay.

I am working on a PR for Google Billing, Robovm implementation, but it is also missing for all other implementations

#### Please select the affected platforms and payment service implementation
- [ ] Amazon
- [X] googlebilling
- [ ] googlepay
- [ ] apple iosmoe
- [X] apple robovm

**Comment by MrStahlfelge** [comment]
I am not sure if Amazon has such a feature, however, the implementation completely lacks any subscription features. Good to have it for the implementations supporting subscriptions.

**Comment by keesvandieren** [comment]
Pull request is merged, we can close the issue
