### ISSUE TITLE
Products not consumed after restore - Huawei

### ISSUE THREAD

**Issue by Berobasket** [libgdx/gdx-pay#222]
#### Issue details, reproduction steps/code
All consumable products needs to be consumed after restore. 

#### Version of gdx-pay and/or relevant dependencies
Gdx-pay - 1.3.0-SNAPSHOT

#### Please select the affected platforms and payment service implementation
- [x] Huawei

**Comment by MrStahlfelge** [comment]
@FStranieri can you take a look at it?

**Comment by Berobasket** [comment]
I've added a pull request with changes https://github.com/libgdx/gdx-pay/pull/224 It would be great if someone could take a look at it.

**Comment by MrStahlfelge** [comment]
The fix is merged, thank you.
