### ISSUE TITLE
Remove gdx-pay-iosmoe-apple

### ISSUE THREAD

**Issue by keesvandieren** [libgdx/gdx-pay#233]
As moe support has been removed from libgdx, also remove it from gdx-pay

Agreed @MrStahlfelge?

Actions:

* remove from codebase
* remove affected platform: " [ ] apple iosmoe" from issue template

**Comment by MrStahlfelge** [comment]
In my opinion, it can be removed. If we ever need it again, the delition can get reverted.

**Comment by yarnee** [comment]
i do not agree, i do use it

**Comment by MrStahlfelge** [comment]
You can continue using it, there's just no new versions available.

**Comment by yarnee** [comment]
hm, i think it' a plot against moe going on... 
It's not only about using it, i definetely will need newer versions, there are only two files to maintain...

**Comment by keesvandieren** [comment]
@yarnee actually moe backend has been removed from libgdx.

Also, moe impl started as a copy from Robovm impl. In the mean time, some bugfixes and features have been added to Robovm impl, but they are not added to moe as nobody of maintainers is using moe so testing is impossible.

Additionally, moe maintainers are no longer active on the forum (https://discuss.multi-os-engine.org/). So it seems that this product is not alive anymore, while Mobivm is going good

**Comment by yarnee** [comment]
@keesvandieren, i'll have to examine the implementation of gdx-pay for RoboVM and MOE to evaluate your statement about an existing deviation you talk about. And even if the  maintainers of moe are not active, there's currently a discussion going on  how the community could participate and evolve the project.  I didn't notice that moe is no more part of the new .11 branch of the libgdx repo, so i probably have to decide how to continue.
