### ISSUE TITLE
PurchaseManagerGoogleBilling.purchaseRestore() doesn't return any purchases since v1.0.0

### ISSUE THREAD

**Issue by pierre-vig** [libgdx/gdx-pay#234]
Hello,

I recently tried to update my android game to the latest gdx-pay version (1.3.0) from the 0.12.1 and I noticed that the callback 
PurchaseManagerGoogleBilling.purchaseRestore() following a restore call PurchaseManager.purchaseRestore() always returns an empty list of purchases now even if there are existing purchases to restore.

After some back and forth testing with the versions I noted that the issue started to happen since the version 1.0.0 of June 2019 (I don't have the problem if I come back to 0.12.1).
I suspect it might be related to the following change [https://github.com/libgdx/gdx-pay/commit/0f9751f277daf0009a467c9e8502424497170fed#diff-6e053a5cb18e1e2609476ad96d8afce2](https://github.com/libgdx/gdx-pay/commit/0f9751f277daf0009a467c9e8502424497170fed#diff-6e053a5cb18e1e2609476ad96d8afce2).

Note that except this issue everything else seems to be fine with the version 1.3.0.

Is there anyone else having the same problem ? If yes, do you have any idea on how to fix it ?

Thank you very much!

Pierre

Version: Since gdx-pay 1.0.0 (June 2019)

#### Please select the affected platforms and payment service implementation
- [ ] Amazon
- [ x] googlebilling
- [ ] googlepay
- [ ] apple iosmoe
- [ ] apple robovm

**Comment by MrStahlfelge** [comment]
Actually, the behaviour IS a fix, see the linked issue #201 on the commit you mentioned.

**Comment by pierre-vig** [comment]
Hello,

Thank you for the quick reply! I checked your issue reference and you are totally right, my bad... My Products were wrongly initialized with OfferType to CONSUMABLE instead ENTITLEMENT and the Consumables bug of the version 0.12.1 was just hiding this real problem of my game.

This is now fixed and I am happy to use the latest version of Gdx-pay.

Thank you very much for the help and time!
