### ISSUE TITLE
java.lang.IllegalStateException: Cannot support OfferType Subscription and other types in the same app

### ISSUE THREAD

**Issue by Trurl101** [libgdx/gdx-pay#235]
Why is it not possible to use Subscription and other offer types simultaneously?

**Comment by Trurl101** [comment]
Ok, I see it is not implemented because its complicated: https://github.com/libgdx/gdx-pay/issues/210

Is there a workaround? Is it possible two use different Purchasemanager? One for Subs and one for the other offertypes?

**Comment by keesvandieren** [comment]
I think it is doable, if you re willing to create a PR for it, we will review it.

Not sure if creating two Purchasemanagers can work, I think it is fairly easy to try?

**Comment by Trurl101** [comment]
It seems to work with two Purchasemanagers. The second one is only for the subscription.

I only tested this on Android.

**Comment by MrStahlfelge** [comment]
As written in the other issue, it should be no problem to deal with it in `PurchaseManager`, it is just some effort to queue the calls correct. You'll have the same effort if you use two PurchaseManagers, so why not improve the project?
