### ISSUE TITLE
iOS app rejected by the App Store

### ISSUE THREAD

**Issue by auraxangelic** [libgdx/gdx-pay#239]
Sorry for making this post. I just can't figure out how to reproduce the issues that the App Store Reviewers are saying exists.

I have successfully uploaded my iOS app via Transporter, and tested in-app purchases successfully with Testflight. I've create a Sandbox user and tested in-app purchases successfully using a development build.

However when I try to submit the app to the App Store, they cite bugs with the in-app purchases and sent me the following screenshots:

![attachment Screenshot-0422-165821](https://user-images.githubusercontent.com/11507961/116485509-62518f00-a859-11eb-91ac-679043812050.png)
<img width="1112" alt="attachment Screenshot-0417-205607" src="https://user-images.githubusercontent.com/11507961/116485510-62ea2580-a859-11eb-9833-43b7a3c8e5b5.png">

The `Error` popup appears whenever `handlePurchaseError` is called on my `PurchaseObserver`. That's the only clue I got. I can't even figure out how to get the `Error` popup to appear during normal use. I can't figure out how to do a `Payment Not Completed` either during normal use.

How are the Apple App Store Reviewers testing this app differently from the way I'm testing it that they are getting this error? How can I reproduce their issue with in-app purchases?

#### Version of gdx-pay and/or relevant dependencies
gdx-pay Version 1.3.1

#### Please select the affected platforms and payment service implementation
- [ ] Amazon
- [ ] googlebilling
- [ ] googlepay
- [x] apple robovm
- [ ] Huawei

**Comment by MrStahlfelge** [comment]
Is "Error" a string you show or is it the actual error message?

**Comment by auraxangelic** [comment]
Good question. It's a string that I show, not the actual message.

**Comment by MrStahlfelge** [comment]
Then you know how to proceed.

**Comment by auraxangelic** [comment]
I guess I do. Does the App Store require that you display the message on the `Throwable`?

**Comment by auraxangelic** [comment]
Is there no way to test the App Store Review scenarios myself? I have to submit the app for review to do the error check?

**Comment by MrStahlfelge** [comment]
For me it looks like they cancelled the purchase and want a proper error message in your game, but I could be wrong. You should always give out proper error messages in any case. If you had done so, you might have an idea what is wrong and what they have done now. No one can know with the information given, so you can either ask them, or try with a better error handling, or both.

**Comment by auraxangelic** [comment]
You were correct in that App Store Review wanted a proper error message. My app has now passed review now that I've used the `message` in the `Throwable`.

**Comment by auraxangelic** [comment]
Thank you.
