### ISSUE TITLE
error: cannot find symbol class PurchaseSystem

### ISSUE THREAD

**Issue by batbug** [libgdx/gdx-pay#243]
Just upgrading my old app, had to upgrade gdx-pay 0.11.2 to the new version 1.3.2 

All went fine for the google version, updates are compiling with no errors, but for ios version I got error: "cannot find symbol class PurchaseSystem". I can see in the release notes for version 1.0.0 that PurchaseSystem was removed, but i cannot find any explanation what to change now in the source code because there is no PurchaseSystem any more. Any help? Thank you in advance.

**Comment by keesvandieren** [comment]
@batbug did you manage to resolve it?

**Comment by batbug** [comment]
@keesvandieren no, we will eventually re-write this part, just a little bit later.

**Comment by keesvandieren** [comment]
Ok, for now I will close the issue.

If you want to write an upgrade guide based on you experience, feel free to provide it.
