### ISSUE TITLE
IAP: gdx-pay successfully instantiated.

### ISSUE THREAD

**Issue by NaN8** [libgdx/gdx-pay#25]
Dear all,

I do not know if I am doing anything wrong, gdx-pay seems to work very well the only thing is when I hit the back button on android, the following log keeps appearing "IAP: gdx-pay successfully instantiated." infinitly... and if I get back to my game the phone completly freeze. It seems that gdx-pay instantiation is called in a loop.... (via reflection??) .

**Comment by noblemaster** [comment]
Where in your code do you initialize IAP, a.k.a. do you call PurchaseSystem?

**Comment by NaN8** [comment]
Hi Noblemaster!

IAP is initalized once in a class derived from ApplicationListener. PurchaseSystem is called yes. Actually the problem arise after I call purchase and after handlepurhase is called back.
If I the delete the GDX.app.postRunnable call in handlepurcahse like in "PayTest.java", the problem is solved.
Why PurchaseSystem is disposed in handlepurchase and why in a Runnable?
                @Override
                public void handlePurchase (Transaction transaction) {
                    message(" - purchased: " + transaction.getIdentifier() + "\n");

                    // dispose the purchase system
                    Gdx.app.postRunnable(new Runnable() {
                        @Override
                        public void run () {
                            message(" - disposing the purchase manager.\n");
                            PurchaseSystem.dispose();
                            message("Testing InApp System: COMPLETED\n");
                        }
                    });
                }

Thank you

**Comment by noblemaster** [comment]
I see! Yes, don't use postRunnable; that's only for the test (otherwise the test wouldn't work). I guess I was too lazy to write a proper test-case with GUI (sorry). You also won't need the other postRunnable(...) that are in the test either. Directly call the different methods in the PurchaseSystem and simply ignore all the postRunnable.

**Comment by NaN8** [comment]
Great! Thank you Noblemaster!
