### ISSUE TITLE
The version of Amazon IAP is quite outdated.

### ISSUE THREAD

**Issue by bitdream** [libgdx/gdx-pay#257]
This IAP 2 is marked as decprecated. 
Any plan to update it?

and handlePurchase and handlePurchaseError look not called no matter what the results are.

Here in AndoridManifest.xml tools:ignore="ExportedReceiver,InvalidPermission" android:exported="false"
It is very wired since the document said:
If your app targets Android 12 or higher, you must explicitly set [android:exported](https://developer.android.com/guide/topics/manifest/activity-element#exported) to true in the MainActivity and ResponseReceiver.

**Comment by bitdream** [comment]
Here in AndoridManifest.xml   tools:ignore="ExportedReceiver,InvalidPermission" android:exported="false"
It is very wired since the document said:
If your app targets Android 12 or higher, you must explicitly set [android:exported](https://developer.android.com/guide/topics/manifest/activity-element#exported) to true in the MainActivity and ResponseReceiver.

**Comment by bitdream** [comment]
I just added a pull request fixing current broken status.
#258

**Comment by keesvandieren** [comment]
Thanks @bitdream ! Just approved the PR. Can you try-out the snapshot and let us know it works for you? Snapshot version will be published into https://oss.sonatype.org/content/repositories/snapshots/

**Comment by bitdream** [comment]
Hi I have tested the current version with AndoridManifest.xml modifications in the pull request from my offline local version.
It worked well in both Amazon Live App Testing and the sandbox app tester with a Kindle Fire HD device.
Not sure how to get and try your snapshot.

**Comment by keesvandieren** [comment]
Merged PR, released to Maven Central. Should be available in 30-60 mins
