### ISSUE TITLE
we should update openIAB to v0.9.8.3

### ISSUE THREAD

**Issue by just4phil** [libgdx/gdx-pay#26]
@noblemaster 
hi chris!
i guess we should update openIAB to v0.9.8.3!?
it seems to use amazon iab 2.01 now....so it could fix issues with the amazon store.
https://github.com/onepf/OpenIAB/releases

bye
phil

**Comment by noblemaster** [comment]
Done! I also uploaded a next "milestone" release to Maven: 0.3.0. Snapshot is now 0.4.0-SNAPSHOT.
