### ISSUE TITLE
GitHub Actions suddenly stops working

### ISSUE THREAD

**Issue by keesvandieren** [libgdx/gdx-pay#266]
GitHub Actions suddenly stop working.

I did solve some issues in the Gradle project, but now it seems [publishing of snapshot](https://github.com/libgdx/gdx-pay/actions/runs/10347000866/job/28636474057#step:7:47) is failing now.

I didn't change anything there, anyone able to have a look? I see @SimonIT and @MrStahlfelge have worked on setup. Your help is welcome.

**Comment by Tom-Ski** [comment]
Should be fixed now, new credentials.
