### ISSUE TITLE
Purchasing a subscription on openiab results in an error

### ISSUE THREAD

**Issue by xoppa** [libgdx/gdx-pay#46]
I'm not very familiar with gdx-pay, but it looks like there's an issue with purchasing a subscription on android/openiab. When purchasing an Offer with type `OfferType.SUBSCRIPTION` it results in the following error:

    IabResult: -1008, IAB returned null purchaseData or dataSignature (response: -1008:Unknown error)

[this link](http://stackoverflow.com/a/16760197/2512687) suggests that [this line](https://github.com/libgdx/gdx-pay/blob/master/gdx-pay-android-openiab/src/com/badlogic/gdx/pay/android/openiab/PurchaseManagerAndroidOpenIAB.java#L303) should call `helper.launchSubscriptionPurchaseFlow` instead when its type is subscription.

**Comment by noblemaster** [comment]
This might be fixed with the latest pull request. Please verify! Thanks.

**Comment by xoppa** [comment]
Thanks. It looks like it hasn't been fixed with latest pull request.

**Comment by alex-dorokhov** [comment]
It was not, I didn't work on it.

**Comment by xoppa** [comment]
Ok, i'll go ahead and reopen this then.
