### ISSUE TITLE
wiki: Page for platform resolvers does not document methods being used

### ISSUE THREAD

**Issue by ShipshapeDetour** [libgdx/gdx-pay#54]
[On this page,](https://github.com/libgdx/gdx-pay/wiki/Integration-example-with-resolvers) the methods `getPlatformResolver()` and `setPlatformResolver()` are used in code examples but are never actually defined or described.

**Comment by just4phil** [comment]
check this out:
https://bitbucket.org/just4phil/gdxpayexample/src/b86dd21d2a06da477c78f2e911d189d69b393890/core/src/com/mygdx/game/?at=master

https://bitbucket.org/just4phil/gdxpayexample/src

http://www.badlogicgames.com/forum/viewtopic.php?f=11&t=19711&p=83745#p83433

i will add this to the wiki
