### ISSUE TITLE
purchaseManager is null but PurchaseSystem.resolve() gives no information

### ISSUE THREAD

**Issue by MaxGyver83** [libgdx/gdx-pay#58]
I'm trying to use gdx-pay 0.5.0 for Android and iOS using the platform resolvers from the wiki. I have no problems with Android. But in iOS, I always get this error when trying to buy something:
`[info] ERROR: gdx-pay: requestPurchase(): purchaseManager == null`
That's not surprising because the purchaseManager is already null when I call the "initializeIAP" method. There I get `"gdx-pay: initializeIAP(): purchaseManager == null => call PurchaseSystem.hasManager()"`. hasManager() (=false) calls getManager() and getManager() calls resolve(). So resolve() should give me some information on why there is no purchaseManager. But I don't get any errors until I click the button that calls the purchase() method.

**Comment by matteberna** [comment]
I will add (possibly related?) that hasManager() does not instantiate a PurchaseManager for me on Android using Proguard, even if I -keep everything. I can only create one by myself and set it.

**Comment by matteberna** [comment]
I will add (possibly related?) that hasManager() does not instantiate a PurchaseManager for me on Android using Proguard, even if I -keep everything. I can only create one by myself and set it.

**Comment by matteberna** [comment]
I will add (possibly related?) that hasManager() does not instantiate a PurchaseManager for me on Android using Proguard, even if I -keep everything. I can only create one by myself and set it.

**Comment by MaxGyver83** [comment]
I think my problem was that I was creating `IOSResolver` in `IOSLauncher.didBecomeActive` and at that time Gdx.app was not yet set. So `Gdx.app.debug` or `Gdx.app.log` didn't work.
