### ISSUE TITLE
consume purchased item

### ISSUE THREAD

**Issue by cococool** [libgdx/gdx-pay#6]
In google play we can't buy item that already owned. How to consume purchased item? 

Thanks for creating this wonderful framework :)

**Comment by AlexanderKharin** [comment]
There is such a problem, if you press the buy button and immediately close the application, then the purchase will not be delivered, and when you return to the application, you will be informed that you already have this content. Hence, we need to manually consume the purchase, for this we need two getOwnedPurchases () methods
and consumerPurchase (String productId).

**Comment by MrStahlfelge** [comment]
What happens if you restore the purchases?
