### ISSUE TITLE
iOS: SKPayment create() is protected -> Constructor made public

### ISSUE THREAD

**Issue by IMakeGames** [libgdx/gdx-pay#63]
Hey,

it seems like starting with RoboVM 1.8, the SKPayment class has changed. SKPayment.create() is made protected, which I think is why PurchaseManageriOSApple produces a NoSuchMethodError exception when running the purchase() method:
`java.lang.NoSuchMethodError: org.robovm.apple.storekit.SKPayment.create(Lorg/robovm/apple/storekit/SKProduct;)Lorg/robovm/apple/storekit/SKPayment;
	at com.badlogic.gdx.pay.ios.apple.PurchaseManageriOSApple.purchase(PurchaseManageriOSApple.java)
	at com.badlogic.gdx.pay.PurchaseSystem.purchase(PurchaseSystem.java)`

I'd say we are required to call the constructor for SKPayment instead.

EDIT: OK, I see now that this is already fixed in 0.6.0-SNAPSHOT. Sorry, and thanks for making this project! :)

**Comment by noblemaster** [comment]
alex-dorokhov provided the fixes just yesterday :-D

**Comment by alex-dorokhov** [comment]
no-no, that was xoppa :)

**Comment by noblemaster** [comment]
My bad: although it seems it was both xoppa & you! Thanks to both you guys :-D

**Comment by LombrozoV** [comment]
Hello. I have this problem also. Can i download new version gdx-pay with use of gradle?  Last version (0.5.0) in the Maven Central updated 13-Aug-2015.

**Comment by alex-dorokhov** [comment]
As it is written in description here: https://github.com/libgdx/gdx-pay, snapshot versions are available via sonatype.
So, add this repository in gradle script: 
```
repositories {
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
}
```
and then use gdx-pay 0.6.0-SNAPSHOT

**Comment by LombrozoV** [comment]
Thank you. It works
