### ISSUE TITLE
Gdx-pay issue

### ISSUE THREAD

**Issue by tzvetkovg** [libgdx/gdx-pay#66]
Hi,

I've managed to implement gdx-pay in my game. However, I am always getting 

"Authentication error, you need to sign in with your google account."

I suspect I've set the wrong google play key. I haven't yet finished my game so I haven't uploaded my game to the google store so I don't have a google key. Is it a google developer key meant or another key? If I don't have a key how can I test gdx-pay in my app? Any info appreciated.

Thank you

**Comment by noblemaster** [comment]
I believe you really need to add the Google developer key for this to work!? Also, I think you need to upload your app to Google Play also (even if you test locally) so it works. You can find the Google Play key under "Services & APIs" for your app. Select the key under "YOUR LICENSE KEY FOR THIS APPLICATION".

**Comment by noblemaster** [comment]
Did you resolve the problem? Please comment; this might be helpful for other as well! - Thanks.

**Comment by tzvetkovg** [comment]
Hi, yes I managed to solve it..my Google licence key was wrong. Thanks for your feedback
