### ISSUE TITLE
Published 0.5.0 POM:s internally depending on gdx-pay SNAPSHOT versions.

### ISSUE THREAD

**Issue by junkdog** [libgdx/gdx-pay#67]
It looks like all/most POM:s referencing the base gdx-pay artifact depend on SNAPSHOT versions.

- [gdx-pay-android-0.5.0.pom](http://central.maven.org/maven2/com/badlogicgames/gdxpay/gdx-pay-android/0.5.0/gdx-pay-android-0.5.0.pom)
- [gdx-pay-server-0.5.0.pom](http://central.maven.org/maven2/com/badlogicgames/gdxpay/gdx-pay-server/0.5.0/gdx-pay-server-0.5.0.pom)
- [gdx-pay-iosrobovm-apple-0.5.0.pom](http://central.maven.org/maven2/com/badlogicgames/gdxpay/gdx-pay-iosrobovm-apple/0.5.0/gdx-pay-iosrobovm-apple-0.5.0.pom)

**Comment by keesvandieren** [comment]
This is also true for 0.6 versions.

https://repo1.maven.org/maven2/com/badlogicgames/gdxpay/gdx-pay-client/0.6.0/gdx-pay-client-0.6.0.pom

**Comment by noblemaster** [comment]
I think that's probably my bad when building the release-files! I believe I need to manually edit the build.gradle and remove "-SNAPSHOT" when building a release, otherwise that "-SNAPSHOT" stays in there? I wonder - I'll try to do that for the next release.

**Comment by noblemaster** [comment]
I believe I fixed it with the latest release 0.7.0 by removing "-SNAPSHOT" while releasing. 

https://repo1.maven.org/maven2/com/badlogicgames/gdxpay/gdx-pay-client/0.7.0/gdx-pay-client-0.7.0.pom

Comments?

**Comment by junkdog** [comment]
Thanks. I haven't have tried to try them out yet, but the dependencies look correct.

**Comment by jtuta** [comment]
This is fixed, can be closed?

**Comment by noblemaster** [comment]
Looks like it's fixed. Thanks for the feedback! - closed :)
