### ISSUE TITLE
ERROR ITMS-90035: "Invalid Signature. A sealed resource is missing or invalid

### ISSUE THREAD

**Issue by supnaobed** [libgdx/gdx-pay#68]
When i use gdx-pay-0.6.0 and gdx-pay-iosrobovm-apple, and upload .ipa use Application Loader i have problem : 

"ERROR ITMS-90035: "Invalid Signature. A sealed resource is missing or invalid. Make sure you have signed your application with a distribution certificate, not an ad hoc certificate or a development certificate. Verify that the code signing settings in Xcode are correct at the target level (which override any values at the project level). Additionally, make sure the bundle you are uploading was built using a Release target in Xcode, not a Simulator target. If you are certain your code signing settings are correct, choose "Clean All" in Xcode, delete the "build" directory in the Finder, and rebuild your release target. For more information, please consult https://developer.apple.com/library/ios/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html",

but when i use gdx-pay-0.5.0 it upload good. i can't use 0.5.0 because it has problem NoSuchMethodError: org.robovm.apple.storekit.SKPayment.createFromProduc

**Comment by xoppa** [comment]
Sounds like a issue with your setup instead of with gdx-pay. How did you verify that this is indeed an issue of gdx-pay? Please include the steps you took and your [sscce](http://sscce.org), if relevant.

**Comment by supnaobed** [comment]
Yes, as it turned out, this problem has nothing to do with the system gdx-pay
