### ISSUE TITLE
gdx-pay (iOS)  transaction.getTransactionData() == null

### ISSUE THREAD

**Issue by LombrozoV** [libgdx/gdx-pay#69]
Hello! I test in-app purchase service in my application (for ios) . Tell me please what's wrong: I made a purchase, it was successfully. But validation at the server not passed because "transaction.getTransactionData() == null".

**Comment by noblemaster** [comment]
I am not sure if that's actually implemented yet for the iOS backend? Maybe some of the iOS-backend developers are able to comment?

**Comment by JavaNoobsyBoobsy** [comment]
I looked at the code and the Base64 decoder seems to be the wrong one. I recommend to use java.util.Base64

**Comment by noblemaster** [comment]
Base64 has different implementations (i.e. slightly different characters):
https://en.wikipedia.org/wiki/Base64#Implementations_and_history

Just make sure to use the corresponding decoder/encoder!
