### ISSUE TITLE
Missing PurchaseObserver & PurchaseSystem in JAR's

### ISSUE THREAD

**Issue by JustGez** [libgdx/gdx-pay#70]
Hi

I just updated my JAR's from 0.5 > 0.6 and com.badlogic.gdx.pay.PurchaseObserver and com.badlogic.gdx.pay.PurchaseSystem are gone.

Unless I am missing something, doesn't this break all the things?

**Comment by alex-dorokhov** [comment]
We have added one more layer of dependency. In your core project you have used gdx-pay as common dependency. Now you should use: gdx-pay-client .
See updated info here: https://github.com/libgdx/gdx-pay/wiki/Maven-Integration

**Comment by JustGez** [comment]
Ahh, ok thank you.
