### ISSUE TITLE
PurchaseSystem.getInformation() returns null for the price with Samsung

### ISSUE THREAD

**Issue by StanDem** [libgdx/gdx-pay#73]
PurchaseSystem.getInformation(SKU).getLocalPricing() returns null when testing for Samsung.
The purchase itself is working fine
Also I've tested the same code with Google and Amazon  - price is returned correctly with the same method.
Please check it.

**Comment by noblemaster** [comment]
Please note as stated in the Javadoc, "getInformation(...)" is not supported on all markets! Either this is (a) not implemented yet in gdx-pay or (b) the market simply doesn't support that kind of information so instead we return "null".
