### ISSUE TITLE
Is gdx-pay compatible to ouya-sdk-2.0.1?

### ISSUE THREAD

**Issue by TomGrill** [libgdx/gdx-pay#74]
I prefer using dependencies instead of manually  copying ouya-sdk.jar to the libs folder.

```
repositories {
    maven {
        url "http://maven.ouya.tv/"
    }
}
dependencies {
    compile 'ouya:ouya-sdk:2.0.1'
}
```

Since the latest ouya-sdk is 2.0.1 which means they did a major release lately, I wonder if using this version of ouya-sdk is breaking gdx-pay. The ouya-sdk in this repository is from 2014 and i cannot figure out which version this is. If 2.0.1 breaks gdx-pay, what is the version in this repository?

**Comment by noblemaster** [comment]
I am not sure? Maybe some folks that helped with the OUYA-backend could comment?

**Comment by keesvandieren** [comment]
Ouya support has been removed from last release, unless someone needs it and wants to document it properly, we won't put it back.
