### ISSUE TITLE
requestPurchaseRestore issue

### ISSUE THREAD

**Issue by tzvetkovg** [libgdx/gdx-pay#76]
Hi,

I am trying to restore purchases. I call requestPurchase(item1) the application exits with the message 

12-13 14:47:08.150: E/OpenIAB(30175): In-app billing error: Unable to buy item, Error response: 7:Item Already Owned

but when I call requestPurchaseRestore() I am not getting this item listed under checkTransaction or handleTransaction methods??

I am using gdx-pay 0.5.0

Any ideas on how to properly check whether an item is already purchased?

**Comment by noblemaster** [comment]
Duplicate of #77.
