### ISSUE TITLE
Support for Android Google Play Store without OpenIAB

### ISSUE THREAD

**Issue by keesvandieren** [libgdx/gdx-pay#80]
gdx-pay-android-openiab has some issues, that might be caused by OpenIAB.

Some stacktraces that might be caused by:

    java.lang.RuntimeException: IabResult: 6, Unable to buy item (response: 6:Error)

   java.lang.RuntimeException: IabResult: -1002, Null data in IAB result (response: -1002:Bad response received)

Provide an alternative implementation that hooks directly into Google Play in app purchase api

**Comment by noblemaster** [comment]
Closed: please use the new Google Play backend instead if you are targeting the Google Play store.
