### ISSUE TITLE
state of gdx-pay-android-googleplay?

### ISSUE THREAD

**Issue by junkdog** [libgdx/gdx-pay#87]
We started out with the openiab backend, but then saw the notice on gdx-pay-android-googleplay:

> - Does not use OpenIAB (OpenIAB is currently unmaintained and has open issues, making payments fail too often)

It might be good to maybe mention the status of openIAB in the main readme too? As I understand it, openIAB is a path best avoided.

What's the state of `gdx-pay-android-googleplay` though? The [status page](https://github.com/libgdx/gdx-pay/blob/master/gdx-pay-android-googleplay/STATUS.md) mentions upcoming refactorings etc. Is it stable enough to use in projects yet?

**Comment by keesvandieren** [comment]
Hi,

We use gdx-pay-android-googleplay in two of our apps.

We have only one product, a non-consumable purchase (so it is a very basic, simple setup). 

We have thoroughly tested it last month, and many vague In-App Billing related errors we had with OpenIAB are gone now.

With OpenIAB we had multiple failed purchases every day. One problem of OpenIAB is that exceptions do not contain root causes, making it very hard to understand whats going on.

During building of -googleplay impl we also found issue https://github.com/libgdx/libgdx/issues/3758, which caused gdx-pay to fail in our app often as well. Upgrade to libgdx 1.9.1 to avoid that issue.

We are dedicated to make it stable and reliable even more, important apps of our company depend on it.

Give it a try, and let us know in case of any questions or issues.

**Comment by keesvandieren** [comment]
I updated the main README.md to reflect the status of OpenIAB.

Also, some TODO's in status of GooglePlay impl have already been implemented in Milestone 1.

Refactorings mentioned in STATUS.md are general gdx-pay refactorings. If we do them (on some we are in discussion) we will provide a migration guide.

**Comment by junkdog** [comment]
Hi, thanks for the quick reply!

Good to hear; the state of OpenIAB flew under our radar. We have consumable purchases too, but I'm guessing it shouldn't be too hard to add on our end.

> Upgrade to libgdx 1.9.1 to avoid that issue.

Nice, will do.

**Comment by keesvandieren** [comment]
We do want to help with consumables.

They are not that hard, subscriptions will be harder.

**Comment by junkdog** [comment]
> We do want to help with consumables.

:+1:  Expect a PR once it's done :)
