### ISSUE TITLE
Github releases: useful for anyone?

### ISSUE THREAD

**Issue by keesvandieren** [libgdx/gdx-pay#89]
Github also provides downloadable releases of artifacts.

When releasing the project, this is a manual action that needs to be done by the developer as well.

I was unaware of that when creating release 0.9.0.

For myself, I never use github releases (always depend on external libraries using a package manager, e.g. Maven or Gradle).

Is anyone using it?

If no one uses it, my proposal is to no longer create these releases.

If they are relevant for users, we should automate its creation. There are plugins for that, such as:
https://github.com/riiid/gradle-github-plugin

**Comment by noblemaster** [comment]
Not sure what you are asking?

**Comment by keesvandieren** [comment]
Simple: should we stop maintaining releases here: https://github.com/libgdx/gdx-pay/releases

**Comment by noblemaster** [comment]
I see! I haven't done anything there. Did you add those? Are those releases not just added automatically by github whenever we tag a release? I usually just tag a release, which takes a few seconds, and be done with it. 

I think it makes sense to tag a new release (was suggested by users earlier). However, I agree with you if this isn't automatic (?), we shouldn't bother to add those manually. People can simply download by tag if they really want a separate release.

**Comment by keesvandieren** [comment]
Automatically created by git tags.
