### ISSUE TITLE
Describe steps needed to release

### ISSUE THREAD

**Issue by keesvandieren** [libgdx/gdx-pay#90]
Describe the steps needed to release.
- What is the expected result of a release?
  - Released jar in Maven Central
  - Tagged release in Git repo
- Which Gradle commands are needed to get there?
- What to do after the release?
  - README.md updates
  - announce new release somewhere?

**Comment by noblemaster** [comment]
Sounds about right. I guess we could create a Wiki page for others interested in doing new releases. They'd need to be given admin rights and also they'd need to sign up to sonatype and given access.

**Comment by keesvandieren** [comment]
Extended the file `release-procedure.md` a bit. Contains enough details to get started.
