### ISSUE TITLE
Not working with Proguard

### ISSUE THREAD

**Issue by coin2** [libgdx/gdx-pay#97]
At all.

I have tried the enhanced settings mentioned.

To give more information:

I've tested it on 3 different devices. It seems like the listener never gets called on a restore or make purchase. 

I'm using API level 23. Without proguard, no problem. I'm using the Google Play, a non-consumable purchase. I wanted to release my game with the new version of this but I'm really not sure what to do now...

Help!

UPDATE: I have fixed it by adding:

-keep class com.badlogic.** {*;}

However you mention in your proguard info page that this is not a great idea, so I'm a bit reluctant to add this. Is it safe to publish my game with this? Thanks!

Forgot to mention, I'm using gdx-pay 0.9.2.

**Comment by noblemaster** [comment]
It's safe. All com.badlogic.* components are open source anyway. Nothing bad is coming out of it.
